-- Generated by scripts/generate-supabase-seed.ts. Do not add secrets.
-- Bootstrap-only seed: reruns are allowed before staff or operational activity exists.
-- Never run this file against an operated database.

begin;

do $$
begin
  if exists(select 1 from public.staff_profiles)
    or exists(select 1 from public.orders)
    or exists(select 1 from public.inventory_movements)
    or exists(select 1 from public.audit_events) then
    raise exception using errcode='55000',message='GD_SEED_OPERATED_DATABASE';
  end if;
end;
$$;

insert into public.site_settings (singleton, accept_orders)
values (true, false)
on conflict (singleton) do nothing;

insert into public.categories (
  slug, name, tagline, description, active, sort_order, publication_status, published_at
)
values
  ('beyblade-x', 'Beyblade X', 'Scatena la tua energia. Domina lo stadio.', 'Tutta la collezione di trottole Beyblade X: attacco, difesa, stamina e bilanciate, pronte per ogni scontro.', true, 0, 'published'::public.publication_status, now()),
  ('lanciatori', 'Lanciatori', 'Potenza e controllo nelle tue mani.', 'Lanciatori a corda e accessori di lancio per colpi precisi e ripetibili.', true, 1, 'published'::public.publication_status, now()),
  ('stadi', 'Stadi', 'Arene per battaglie epiche.', 'Stadi e set arena ufficiali Beyblade X, studiati per urti estremi e KO spettacolari.', true, 2, 'published'::public.publication_status, now()),
  ('accessori', 'Accessori', 'Personalizza. Migliora. Vinci.', 'Attrezzi, custodie e ricambi per tenere il tuo arsenale sempre pronto.', true, 3, 'published'::public.publication_status, now())
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  sort_order = excluded.sort_order;

with seed(category_slug, slug, sku, preorder_allocation, name, tagline, description, price_cents, compare_at_price_cents, blade_type, rating, review_count, sort_order) as (
  values
  ('beyblade-x', 'cobalt-dragoon-2-60c', 'COBALT-DRAGOON-2-60C', 10, 'Cobalt Dragoon 2-60C', 'Attacco left-spin. Smash devastante.', 'Cobalt Dragoon 2-60C è una trottola d''attacco a rotazione sinistra (left-spin): quattro lame inclinate verso l''alto concentrano uno Smash Attack estremo, mentre il Ratchet 2-60 e il Bit Cyclone bilanciano velocità e stabilità. Lo starter include il lanciatore a corda left-spin dedicato.', 2550, null, 'attacco', 0, 0, 0),
  ('beyblade-x', 'soar-phoenix-9-60gf', 'SOAR-PHOENIX-9-60GF', 60, 'Soar Phoenix 9-60GF', 'Upper attack. Colpisci verso l''alto.', 'Soar Phoenix 9-60GF è una trottola d''attacco a tre lame che salgono verso l''alto per un Upper Attack capace di sollevare l''avversario, unito allo Smash che lo spinge fuori arena. Tra le blade più pesanti della serie. Lo starter include il lanciatore a corda.', 3200, null, 'attacco', 0, 0, 1),
  ('beyblade-x', 'saber-samurai-2-70l', 'SABER-SAMURAI-2-70L', 30, 'Saber Samurai 2-70L', 'Doppia lama. Colpi da katana.', 'Saber Samurai 2-70L (linea UX) è una trottola d''attacco: le due protuberanze si ritraggono a metà battaglia, passando da colpi ripetuti in stile katana a un singolo impatto "tachi" per KO improvvisi. Lo starter include il lanciatore con impugnatura (grip).', 2790, null, 'attacco', 0, 0, 2),
  ('beyblade-x', 'blast-pegasus-a-tr', 'BLAST-PEGASUS-A-TR', 30, 'Blast Pegasus A Tr', 'Attacco portatile. Clip & Rip Launcher.', 'Blast Pegasus A Tr è una trottola d''attacco a rotazione destra della linea CX, venduta con il Clip & Rip Launcher: un lanciatore portatile che si aggancia a cintura e zaino e ripone il ripcord all''interno. Richiede un Beystadium Beyblade X (venduto separatamente).', 2950, null, 'attacco', 0, 0, 3),
  ('stadi', 'drop-attack-battle-set', 'DROP-ATTACK-BATTLE-SET', 30, 'Drop Attack Battle Set', 'Stadio + 2 trottole + 2 lanciatori.', 'Il Drop Attack Battle Set include tutto per giocare: il Beystadium con X-Celerator Rail rialzato che porta le trottole in alto per farle piombare sull''avversario, due trottole (Impact Drake 9-60LR d''attacco e Hover Wyvern 3-85N di difesa) e due lanciatori a corda.', 4650, null, null, 0, 0, 4),
  ('stadi', 'sneak-attack-battle-set', 'SNEAK-ATTACK-BATTLE-SET', 30, 'Sneak Attack Battle Set', 'Stadio verde + 2 trottole + 2 lanciatori.', 'Il Sneak Attack Battle Set mette in scatola tutto per il primo scontro: il Beystadium con rail a scomparsa che devia le trottole in una nuova direzione, due trottole (Rampart Aegis GB di stamina e Cutter Shinobi LF d''attacco) e due lanciatori a corda.', 4500, null, null, 0, 0, 5)
)
insert into public.products (
  category_id, slug, sku, name, tagline, description, price_cents,
  compare_at_price_cents, publication_status, active, stock_quantity,
  availability_override, preorder_allocation, blade_type, rating, review_count, sort_order
)
select
  category.id,
  seed.slug,
  seed.sku,
  seed.name,
  seed.tagline,
  seed.description,
  seed.price_cents,
  seed.compare_at_price_cents::integer,
  'published'::public.publication_status,
  true,
  0 as stock_quantity,
  'preorder'::public.availability_override,
  seed.preorder_allocation,
  seed.blade_type::public.blade_type,
  seed.rating,
  seed.review_count,
  seed.sort_order
from seed
join public.categories as category on category.slug = seed.category_slug
on conflict (slug) do update set
  category_id = excluded.category_id,
  sku = excluded.sku,
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  blade_type = excluded.blade_type,
  rating = excluded.rating,
  review_count = excluded.review_count,
  sort_order = excluded.sort_order;

with seed(product_slug, src, width, height, alt, sort_order) as (
  values
  ('cobalt-dragoon-2-60c', '/products/cobalt-dragoon-2-60c.webp', 1000, 1000, 'Confezione Beyblade X Cobalt Dragoon 2-60C con lanciatore a corda blu e trottola', 0),
  ('soar-phoenix-9-60gf', '/products/soar-phoenix-9-60gf.webp', 1000, 1000, 'Confezione Beyblade X Soar Phoenix 9-60GF rossa con lanciatore e trottola', 0),
  ('saber-samurai-2-70l', '/products/saber-samurai-2-70l.webp', 1000, 1000, 'Confezione Beyblade X Saber Samurai 2-70L viola con lanciatore a impugnatura e trottola', 0),
  ('blast-pegasus-a-tr', '/products/blast-pegasus-a-tr.webp', 1000, 1000, 'Beyblade X Blast Pegasus A Tr con Clip & Rip Launcher verde e trottola', 0),
  ('drop-attack-battle-set', '/products/drop-attack-battle-set.webp', 1000, 1000, 'Beyblade X Drop Attack Battle Set: stadio blu, due trottole e due lanciatori', 0),
  ('sneak-attack-battle-set', '/products/sneak-attack-battle-set.webp', 1000, 1000, 'Beyblade X Sneak Attack Battle Set: stadio verde, due trottole e due lanciatori', 0)
)
insert into public.product_images (product_id, src, width, height, alt, sort_order, published)
select product.id, seed.src, seed.width, seed.height, seed.alt, seed.sort_order, true
from seed
join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  src = excluded.src,
  width = excluded.width,
  height = excluded.height,
  alt = excluded.alt;

with seed(product_slug, label, value, sort_order) as (
  values
  ('cobalt-dragoon-2-60c', 'Tipo', 'Attacco (left-spin)', 0),
  ('cobalt-dragoon-2-60c', 'Sistema', 'Beyblade X', 1),
  ('cobalt-dragoon-2-60c', 'Codice', '2-60C', 2),
  ('cobalt-dragoon-2-60c', 'Componenti', '1 trottola, 1 lanciatore a corda', 3),
  ('cobalt-dragoon-2-60c', 'Materiale', 'Plastica e metallo', 4),
  ('soar-phoenix-9-60gf', 'Tipo', 'Attacco', 0),
  ('soar-phoenix-9-60gf', 'Sistema', 'Beyblade X', 1),
  ('soar-phoenix-9-60gf', 'Codice', '9-60GF', 2),
  ('soar-phoenix-9-60gf', 'Componenti', '1 trottola, 1 lanciatore a corda', 3),
  ('soar-phoenix-9-60gf', 'Materiale', 'Plastica e metallo', 4),
  ('saber-samurai-2-70l', 'Tipo', 'Attacco', 0),
  ('saber-samurai-2-70l', 'Sistema', 'Beyblade X', 1),
  ('saber-samurai-2-70l', 'Linea', 'UX (UX-09)', 2),
  ('saber-samurai-2-70l', 'Codice', '2-70L', 3),
  ('saber-samurai-2-70l', 'Componenti', '1 trottola, 1 lanciatore con impugnatura', 4),
  ('blast-pegasus-a-tr', 'Tipo', 'Attacco', 0),
  ('blast-pegasus-a-tr', 'Sistema', 'Beyblade X', 1),
  ('blast-pegasus-a-tr', 'Linea', 'CX', 2),
  ('blast-pegasus-a-tr', 'Componenti', '1 trottola, 1 Clip & Rip Launcher', 3),
  ('blast-pegasus-a-tr', 'Nota', 'Richiede un Beystadium (venduto a parte)', 4),
  ('drop-attack-battle-set', 'Tipo', 'Kit arena', 0),
  ('drop-attack-battle-set', 'Sistema', 'Beyblade X', 1),
  ('drop-attack-battle-set', 'Componenti', '1 stadio, 2 trottole, 2 lanciatori', 2),
  ('drop-attack-battle-set', 'Trottole incluse', 'Impact Drake 9-60LR, Hover Wyvern 3-85N', 3),
  ('drop-attack-battle-set', 'Materiale', 'Plastica e metallo', 4),
  ('sneak-attack-battle-set', 'Tipo', 'Kit arena', 0),
  ('sneak-attack-battle-set', 'Sistema', 'Beyblade X', 1),
  ('sneak-attack-battle-set', 'Componenti', '1 stadio, 2 trottole, 2 lanciatori', 2),
  ('sneak-attack-battle-set', 'Trottole incluse', 'Rampart Aegis GB, Cutter Shinobi LF', 3),
  ('sneak-attack-battle-set', 'Materiale', 'Plastica e metallo', 4)
)
insert into public.product_specs (product_id, label, value, sort_order)
select product.id, seed.label, seed.value, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  label = excluded.label,
  value = excluded.value;

with seed(product_slug, title, description, sort_order) as (
  values
  ('cobalt-dragoon-2-60c', 'Rotazione sinistra', 'Left-spin che spiazza gli assetti a rotazione destra', 0),
  ('cobalt-dragoon-2-60c', 'Smash estremo', 'Quattro lame inclinate per KO potenti', 1),
  ('cobalt-dragoon-2-60c', 'Starter completo', 'Include il lanciatore a corda dedicato', 2),
  ('cobalt-dragoon-2-60c', 'Compatibile Beyblade X', 'Blade, Ratchet e Bit intercambiabili con la serie', 3),
  ('soar-phoenix-9-60gf', 'Upper Attack', 'Le tre lame sollevano l''avversario da terra', 0),
  ('soar-phoenix-9-60gf', 'Peso elevato', 'Massa che domina i confronti d''attacco', 1),
  ('soar-phoenix-9-60gf', 'Starter completo', 'Include il lanciatore a corda', 2),
  ('soar-phoenix-9-60gf', 'Compatibile Beyblade X', 'Blade, Ratchet e Bit intercambiabili con la serie', 3),
  ('saber-samurai-2-70l', 'Gimmick a doppia modalità', 'Da colpi ripetuti a singolo impatto tachi', 0),
  ('saber-samurai-2-70l', 'Linea UX', 'Meccanica esclusiva della Unique Line', 1),
  ('saber-samurai-2-70l', 'Lanciatore grip incluso', 'Impugnatura per lanci potenti e stabili', 2),
  ('saber-samurai-2-70l', 'Compatibile Beyblade X', 'Blade, Ratchet e Bit intercambiabili con la serie', 3),
  ('blast-pegasus-a-tr', 'Clip & Rip Launcher', 'Lanciatore portatile: si aggancia e riponi il ripcord', 0),
  ('blast-pegasus-a-tr', 'Linea CX', 'Trottola d''attacco a rotazione destra', 1),
  ('blast-pegasus-a-tr', 'X-Celerator', 'Accelera sull''X-Celerator Rail dello stadio', 2),
  ('blast-pegasus-a-tr', 'Compatibile Beyblade X', 'Blade, Ratchet e Bit intercambiabili con la serie', 3),
  ('drop-attack-battle-set', 'X-Celerator Rail rialzato', 'Porta le trottole in alto per il Drop Attack', 0),
  ('drop-attack-battle-set', 'Set completo', 'Stadio, due trottole e due lanciatori pronti al gioco', 1),
  ('drop-attack-battle-set', 'Impact Drake + Hover Wyvern', 'Un assetto d''attacco e uno di difesa', 2),
  ('drop-attack-battle-set', 'Compatibile Beyblade X', 'Usa tutte le trottole e parti della serie', 3),
  ('sneak-attack-battle-set', 'Rail a scomparsa', 'Devia le trottole in una nuova direzione a sorpresa', 0),
  ('sneak-attack-battle-set', 'Set completo', 'Stadio, due trottole e due lanciatori pronti al gioco', 1),
  ('sneak-attack-battle-set', 'Rampart Aegis + Cutter Shinobi', 'Un assetto di stamina e uno d''attacco', 2),
  ('sneak-attack-battle-set', 'Compatibile Beyblade X', 'Usa tutte le trottole e parti della serie', 3)
)
insert into public.product_features (product_id, title, description, sort_order)
select product.id, seed.title, seed.description, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  title = excluded.title,
  description = excluded.description;

with seed(product_slug, content, sort_order) as (
  values
  ('cobalt-dragoon-2-60c', '1 × Trottola Cobalt Dragoon 2-60C', 0),
  ('cobalt-dragoon-2-60c', '1 × Lanciatore a corda left-spin', 1),
  ('cobalt-dragoon-2-60c', 'Manuale', 2),
  ('soar-phoenix-9-60gf', '1 × Trottola Soar Phoenix 9-60GF', 0),
  ('soar-phoenix-9-60gf', '1 × Lanciatore a corda', 1),
  ('soar-phoenix-9-60gf', 'Manuale', 2),
  ('saber-samurai-2-70l', '1 × Trottola Saber Samurai 2-70L', 0),
  ('saber-samurai-2-70l', '1 × Lanciatore con impugnatura', 1),
  ('saber-samurai-2-70l', '1 × Winder', 2),
  ('saber-samurai-2-70l', 'Manuale', 3),
  ('blast-pegasus-a-tr', '1 × Trottola Blast Pegasus A Tr', 0),
  ('blast-pegasus-a-tr', '1 × Clip & Rip Launcher', 1),
  ('blast-pegasus-a-tr', '1 × Ripcord', 2),
  ('blast-pegasus-a-tr', 'Manuale', 3),
  ('drop-attack-battle-set', '1 × Beystadium Drop Attack', 0),
  ('drop-attack-battle-set', '1 × Impact Drake 9-60LR', 1),
  ('drop-attack-battle-set', '1 × Hover Wyvern 3-85N', 2),
  ('drop-attack-battle-set', '2 × Lanciatori a corda', 3),
  ('drop-attack-battle-set', 'Manuale di gioco', 4),
  ('sneak-attack-battle-set', '1 × Beystadium Sneak Attack', 0),
  ('sneak-attack-battle-set', '1 × Rampart Aegis GB', 1),
  ('sneak-attack-battle-set', '1 × Cutter Shinobi LF', 2),
  ('sneak-attack-battle-set', '2 × Lanciatori a corda', 3),
  ('sneak-attack-battle-set', 'Manuale di gioco', 4)
)
insert into public.product_box_contents (product_id, content, sort_order)
select product.id, seed.content, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  content = excluded.content;



with seed(product_slug, related_slug, sort_order) as (
  values
  ('cobalt-dragoon-2-60c', 'blast-pegasus-a-tr', 0),
  ('cobalt-dragoon-2-60c', 'soar-phoenix-9-60gf', 1),
  ('cobalt-dragoon-2-60c', 'saber-samurai-2-70l', 2),
  ('soar-phoenix-9-60gf', 'cobalt-dragoon-2-60c', 0),
  ('soar-phoenix-9-60gf', 'blast-pegasus-a-tr', 1),
  ('soar-phoenix-9-60gf', 'saber-samurai-2-70l', 2),
  ('saber-samurai-2-70l', 'cobalt-dragoon-2-60c', 0),
  ('saber-samurai-2-70l', 'soar-phoenix-9-60gf', 1),
  ('saber-samurai-2-70l', 'blast-pegasus-a-tr', 2),
  ('blast-pegasus-a-tr', 'cobalt-dragoon-2-60c', 0),
  ('blast-pegasus-a-tr', 'soar-phoenix-9-60gf', 1),
  ('blast-pegasus-a-tr', 'saber-samurai-2-70l', 2),
  ('drop-attack-battle-set', 'sneak-attack-battle-set', 0),
  ('drop-attack-battle-set', 'cobalt-dragoon-2-60c', 1),
  ('drop-attack-battle-set', 'soar-phoenix-9-60gf', 2),
  ('sneak-attack-battle-set', 'drop-attack-battle-set', 0),
  ('sneak-attack-battle-set', 'cobalt-dragoon-2-60c', 1),
  ('sneak-attack-battle-set', 'saber-samurai-2-70l', 2)
)
insert into public.product_relations (product_id, related_product_id, relation_type, sort_order)
select product.id, related.id, 'related'::public.product_relation_type, seed.sort_order
from seed
join public.products as product on product.slug = seed.product_slug
join public.products as related on related.slug = seed.related_slug
on conflict (product_id, related_product_id, relation_type) do update set
  sort_order = excluded.sort_order;

insert into public.bundles (
  slug, eyebrow, title_line_one, title_line_two, description,
  price_cents, compare_at_price_cents, hero_product_id, active
)
select
  'bundle-campione',
  'Bundle campione',
  'Scatena il',
  'tuo potenziale.',
  'Uno stadio e le trottole ad alte prestazioni per iniziare a dominare l''arena.',
  9900,
  10400,
  product.id,
  true
from public.products as product
where product.slug = 'drop-attack-battle-set'
on conflict (slug) do update set
  eyebrow = excluded.eyebrow,
  title_line_one = excluded.title_line_one,
  title_line_two = excluded.title_line_two,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  hero_product_id = excluded.hero_product_id;

with seed(bundle_slug, product_slug, quantity, sort_order) as (
  values
  ('bundle-campione', 'drop-attack-battle-set', 1, 0),
  ('bundle-campione', 'cobalt-dragoon-2-60c', 1, 1),
  ('bundle-campione', 'soar-phoenix-9-60gf', 1, 2)
)
insert into public.bundle_items (bundle_id, product_id, quantity, sort_order)
select bundle.id, product.id, seed.quantity, seed.sort_order
from seed
join public.bundles as bundle on bundle.slug = seed.bundle_slug
join public.products as product on product.slug = seed.product_slug
on conflict (bundle_id, product_id) do update set
  quantity = excluded.quantity,
  sort_order = excluded.sort_order;

insert into public.homepage_sections (
  section_key, section_type, eyebrow, title, subtitle, description, cta_label, cta_href,
  publication_status, published_at, active, sort_order
)
values
  ('hero', 'hero', 'Beyblade X', 'Pronti alla battaglia. Nati per vincere.', null, 'Prodotti originali, drop esclusivi e una community di appassionati. Massima performance, ogni battaglia.', 'Esplora il catalogo', '/negozio', 'published'::public.publication_status, now(), true, 0),
  ('categories', 'categories', null, 'Categorie', null, null, null, null, 'published'::public.publication_status, now(), true, 1),
  ('status-legend', 'status_legend', null, 'Legenda della disponibilità', null, null, null, null, 'published'::public.publication_status, now(), true, 2),
  ('featured-products', 'featured_products', null, 'In evidenza', null, null, 'Vedi tutto', '/negozio', 'published'::public.publication_status, now(), true, 3),
  ('trust', 'trust', null, 'Prodotti originali. Spedizione veloce. Resi semplici.', null, null, null, null, 'published'::public.publication_status, now(), true, 4),
  ('latest-drops', 'latest_drops', null, 'Ultimi drop', null, null, 'Scopri i nuovi arrivi', '/negozio?sort=novita', 'published'::public.publication_status, now(), true, 5),
  ('bestsellers', 'bestsellers', null, 'Più venduti', null, null, 'Vedi Beyblade X', '/negozio/beyblade-x', 'published'::public.publication_status, now(), true, 6),
  ('champion-bundle', 'bundle', null, 'Bundle campione', null, null, null, null, 'published'::public.publication_status, now(), true, 7),
  ('competitive-picks', 'competitive_products', null, 'Scelti per il competitivo', null, null, 'Guida alle combo', '/negozio/beyblade-x', 'published'::public.publication_status, now(), true, 8),
  ('club', 'club', null, 'GEAR//DROP Club', 'Entra nel club. Sblocca vantaggi esclusivi.', null, 'Scopri di più', '/account', 'published'::public.publication_status, now(), true, 9)
on conflict (section_key) do update set
  section_type = excluded.section_type,
  eyebrow = excluded.eyebrow,
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  cta_label = excluded.cta_label,
  cta_href = excluded.cta_href;

delete from public.homepage_section_products as target
using public.homepage_sections as section
where target.section_id = section.id
  and section.section_key in ('hero', 'categories', 'status-legend', 'featured-products', 'trust', 'latest-drops', 'bestsellers', 'champion-bundle', 'competitive-picks', 'club');

with seed(section_key, product_slug, sort_order) as (
  values
  ('featured-products', 'cobalt-dragoon-2-60c', 0),
  ('featured-products', 'soar-phoenix-9-60gf', 1),
  ('featured-products', 'saber-samurai-2-70l', 2),
  ('featured-products', 'blast-pegasus-a-tr', 3),
  ('featured-products', 'drop-attack-battle-set', 4),
  ('featured-products', 'sneak-attack-battle-set', 5),
  ('latest-drops', 'cobalt-dragoon-2-60c', 0),
  ('latest-drops', 'soar-phoenix-9-60gf', 1),
  ('latest-drops', 'saber-samurai-2-70l', 2),
  ('latest-drops', 'blast-pegasus-a-tr', 3),
  ('latest-drops', 'drop-attack-battle-set', 4),
  ('latest-drops', 'sneak-attack-battle-set', 5),
  ('bestsellers', 'cobalt-dragoon-2-60c', 0),
  ('bestsellers', 'soar-phoenix-9-60gf', 1),
  ('bestsellers', 'saber-samurai-2-70l', 2),
  ('bestsellers', 'blast-pegasus-a-tr', 3),
  ('bestsellers', 'drop-attack-battle-set', 4),
  ('bestsellers', 'sneak-attack-battle-set', 5),
  ('competitive-picks', 'cobalt-dragoon-2-60c', 0),
  ('competitive-picks', 'soar-phoenix-9-60gf', 1),
  ('competitive-picks', 'saber-samurai-2-70l', 2),
  ('competitive-picks', 'blast-pegasus-a-tr', 3),
  ('competitive-picks', 'drop-attack-battle-set', 4),
  ('competitive-picks', 'sneak-attack-battle-set', 5)
)
insert into public.homepage_section_products(section_id, product_id, sort_order)
select section.id, product.id, seed.sort_order
from seed
join public.homepage_sections as section on section.section_key = seed.section_key
join public.products as product on product.slug = seed.product_slug
on conflict (section_id, product_id) do update set sort_order = excluded.sort_order;

delete from public.homepage_section_categories as target
using public.homepage_sections as section
where target.section_id = section.id
  and section.section_key in ('hero', 'categories', 'status-legend', 'featured-products', 'trust', 'latest-drops', 'bestsellers', 'champion-bundle', 'competitive-picks', 'club');

with seed(section_key, category_slug, sort_order) as (
  values
  ('categories', 'beyblade-x', 0),
  ('categories', 'lanciatori', 1),
  ('categories', 'stadi', 2),
  ('categories', 'accessori', 3)
)
insert into public.homepage_section_categories(section_id, category_id, sort_order)
select section.id, category.id, seed.sort_order
from seed
join public.homepage_sections as section on section.section_key = seed.section_key
join public.categories as category on category.slug = seed.category_slug
on conflict (section_id, category_id) do update set sort_order = excluded.sort_order;

delete from public.homepage_section_bundles as target
using public.homepage_sections as section
where target.section_id = section.id
  and section.section_key in ('hero', 'categories', 'status-legend', 'featured-products', 'trust', 'latest-drops', 'bestsellers', 'champion-bundle', 'competitive-picks', 'club');

with seed(section_key, bundle_slug, sort_order) as (
  values
  ('champion-bundle', 'bundle-campione', 0)
)
insert into public.homepage_section_bundles(section_id, bundle_id, sort_order)
select section.id, bundle.id, seed.sort_order
from seed
join public.homepage_sections as section on section.section_key = seed.section_key
join public.bundles as bundle on bundle.slug = seed.bundle_slug
on conflict (section_id, bundle_id) do update set sort_order = excluded.sort_order;

insert into public.content_pages (
  slug, title, excerpt, markdown_source, format, seo_title, seo_description,
  publication_status, published_at, active, sort_order
)
values
  ('faq', 'Domande frequenti', 'Le risposte alle domande che ci arrivano più spesso.', '## I prodotti sono originali?

Sì. Vendiamo esclusivamente prodotti ufficiali Beyblade X. Nessuna replica, nessun articolo non autorizzato.

## Quanto costa la spedizione?

La spedizione standard è gratuita per ordini superiori a 59€. Sotto questa soglia si applica una tariffa fissa di 4,90€.

## Cosa significa “in arrivo”?

Il prodotto è già ordinato e sta per entrare in magazzino. Puoi acquistarlo subito: lo spediamo appena disponibile.

## Cosa significa “pre-ordine”?

Il prodotto non è ancora uscito. Ordinandolo ora ti assicuri una unità del primo stock e lo spediamo il giorno dell''uscita.

## Posso cambiare idea?

Hai 30 giorni dalla consegna per richiedere il reso. Vedi la pagina Resi e rimborsi.', 'markdown'::public.content_format, 'Domande frequenti', 'Le risposte alle domande che ci arrivano più spesso.', 'published'::public.publication_status, now(), true, 0),
  ('spedizioni', 'Spedizioni', 'Come e quando arriva il tuo ordine.', '## Tempi di consegna

Gli ordini confermati entro le 14:00 nei giorni lavorativi partono in giornata.

La consegna standard avviene in 24/48h in tutta Italia. Nelle isole e nelle zone disagiate può servire un giorno in più.

## Costi

Spedizione gratuita per ordini superiori a 59€.

Sotto la soglia, la spedizione standard costa 4,90€. L''opzione Express è disponibile in checkout con un supplemento di 6,90€.

## Tracciamento

Ricevi il codice di tracciamento via email appena il pacco lascia il magazzino.

## Prodotti in pre-ordine

Se il tuo ordine contiene un pre-ordine, spediamo tutto insieme alla data di uscita. Se preferisci ricevere prima il resto, effettua due ordini separati.', 'markdown'::public.content_format, 'Spedizioni', 'Come e quando arriva il tuo ordine.', 'published'::public.publication_status, now(), true, 1),
  ('resi', 'Resi e rimborsi', 'Se qualcosa non va, si risolve.', '## Hai 30 giorni

Puoi richiedere il reso entro 30 giorni dalla consegna, per qualsiasi motivo, purché il prodotto sia integro e nella confezione originale.

## Come richiederlo

Scrivici dalla pagina Contatti indicando il numero d''ordine. Ti inviamo l''etichetta di reso e le istruzioni.

## Rimborsi

Il rimborso viene emesso entro 5 giorni lavorativi dalla ricezione del reso, sullo stesso metodo di pagamento usato per l''ordine.

## Prodotto difettoso

Se il prodotto arriva danneggiato o difettoso, la spedizione di reso è a nostro carico e la sostituzione è prioritaria.', 'markdown'::public.content_format, 'Resi e rimborsi', 'Se qualcosa non va, si risolve.', 'published'::public.publication_status, now(), true, 2),
  ('contatti', 'Contattaci', 'Siamo blader anche noi: rispondiamo da persone, non da bot.', '## Assistenza ordini

Per qualsiasi domanda su un ordine, scrivi a supporto@geardrop.it indicando il numero d''ordine.

Rispondiamo entro un giorno lavorativo.

## Community

Per consigli su combo e assetti, la community è il posto giusto: ci trovi sui canali social.

## Collaborazioni

Organizzi tornei o gestisci un negozio? Scrivi a partner@geardrop.it.', 'markdown'::public.content_format, 'Contattaci', 'Siamo blader anche noi: rispondiamo da persone, non da bot.', 'published'::public.publication_status, now(), true, 3),
  ('termini', 'Termini e condizioni', 'Le regole di utilizzo del sito e di acquisto.', '> Testo segnaposto. Questa pagina non è stata redatta né revisionata da un legale e non ha valore contrattuale: va sostituita prima della messa online.

## Oggetto

Questa sezione descriverà l''ambito del contratto di vendita tra GEAR//DROP e il cliente.

## Ordini e prezzi

Questa sezione descriverà conclusione dell''ordine, disponibilità, prezzi e IVA.

## Diritto di recesso

Questa sezione riporterà il recesso previsto dal Codice del Consumo.

## Garanzia legale di conformità

Questa sezione riporterà la garanzia legale applicabile.', 'markdown'::public.content_format, 'Termini e condizioni', 'Le regole di utilizzo del sito e di acquisto.', 'published'::public.publication_status, now(), true, 4),
  ('privacy', 'Privacy e cookie', 'Come trattiamo i dati personali.', '> Testo segnaposto. Questa pagina non è stata redatta né revisionata da un legale e non ha valore contrattuale: va sostituita prima della messa online.

## Titolare del trattamento

Questa sezione indicherà il titolare e i contatti.

## Dati raccolti e finalità

Questa sezione elencherà dati, finalità e basi giuridiche.

## Cookie

Questa sezione elencherà i cookie usati e le modalità di consenso.

## Diritti dell''interessato

Questa sezione descriverà i diritti previsti dal GDPR.', 'markdown'::public.content_format, 'Privacy e cookie', 'Come trattiamo i dati personali.', 'published'::public.publication_status, now(), true, 5),
  ('chi-siamo', 'Chi siamo', 'GEAR//DROP è uno store indipendente costruito da blader per blader.', '## Nati nello stadio. Cresciuti nella community.

GEAR//DROP è uno store indipendente costruito da blader per blader. Un posto dove trovare i pezzi giusti, sapere davvero cosa stai comprando e riceverlo in fretta.

## Come lavoriamo

### Solo prodotti originali

Vendiamo esclusivamente Beyblade X ufficiali. Nessuna replica: quello che compri è quello che porti in torneo.

### Drop, non scaffali

Ogni settimana entrano nuovi pezzi. Quando un drop finisce, finisce: preferiamo dirlo che fingere disponibilità.

### Parliamo la lingua del gioco

Attacco, difesa, stamina, bilanciato: se ci chiedi un consiglio su un assetto, sappiamo di cosa parli.

### Community prima di tutto

Siamo nati dalla community italiana di Beyblade X e continuiamo a farne parte, dentro e fuori dallo stadio.', 'markdown'::public.content_format, 'Chi siamo', 'GEAR//DROP è il punto di riferimento italiano per Beyblade X: prodotti originali, spedizione veloce, community.', 'published'::public.publication_status, now(), true, 6)
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  markdown_source = excluded.markdown_source,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description;

insert into public.navigation_menus(menu_key, label, publication_status, published_at, active)
values
  ('main', 'Navigazione principale', 'published'::public.publication_status, now(), true)
on conflict (menu_key) do update set label = excluded.label;

delete from public.navigation_items as item
using public.navigation_menus as menu
where item.menu_id = menu.id
  and menu.menu_key in ('main');

with seed(menu_key, label, href, sort_order) as (
  values
  ('main', 'Negozio', '/negozio', 0),
  ('main', 'Beyblade X', '/negozio/beyblade-x', 1),
  ('main', 'Lanciatori', '/negozio/lanciatori', 2),
  ('main', 'Stadi', '/negozio/stadi', 3),
  ('main', 'Accessori', '/negozio/accessori', 4),
  ('main', 'Nuovi arrivi', '/negozio?sort=novita', 5),
  ('main', 'Offerte', '/negozio?stock=disponibile', 6)
)
insert into public.navigation_items(menu_id, parent_id, label, href, active, sort_order)
select menu.id, null, seed.label, seed.href, true, seed.sort_order
from seed join public.navigation_menus as menu on menu.menu_key = seed.menu_key;

insert into public.footer_columns(column_key, title, publication_status, published_at, active, sort_order)
values
  ('shop', 'Negozio', 'published'::public.publication_status, now(), true, 0),
  ('help', 'Aiuto', 'published'::public.publication_status, now(), true, 1),
  ('account', 'Account', 'published'::public.publication_status, now(), true, 2),
  ('info', 'Info', 'published'::public.publication_status, now(), true, 3)
on conflict (column_key) do update set
  title = excluded.title;

delete from public.footer_items as item
using public.footer_columns as column_row
where item.column_id = column_row.id
  and column_row.column_key in ('shop', 'help', 'account', 'info');

with seed(column_key, label, href, sort_order) as (
  values
  ('shop', 'Beyblade X', '/negozio/beyblade-x', 0),
  ('shop', 'Lanciatori', '/negozio/lanciatori', 1),
  ('shop', 'Stadi', '/negozio/stadi', 2),
  ('shop', 'Accessori', '/negozio/accessori', 3),
  ('shop', 'Nuovi arrivi', '/negozio?sort=novita', 4),
  ('help', 'FAQ', '/assistenza/faq', 0),
  ('help', 'Spedizioni', '/assistenza/spedizioni', 1),
  ('help', 'Resi e rimborsi', '/assistenza/resi', 2),
  ('help', 'Contattaci', '/assistenza/contatti', 3),
  ('account', 'Il mio account', '/account', 0),
  ('account', 'Lista desideri', '/preferiti', 1),
  ('account', 'Carrello', '/carrello', 2),
  ('info', 'Chi siamo', '/chi-siamo', 0),
  ('info', 'Termini e condizioni', '/legale/termini', 1),
  ('info', 'Privacy e cookie', '/legale/privacy', 2)
)
insert into public.footer_items(column_id, label, href, active, sort_order)
select column_row.id, seed.label, seed.href, true, seed.sort_order
from seed join public.footer_columns as column_row on column_row.column_key = seed.column_key;

-- Fill reviewed public identity only while migration defaults are still blank.
-- Later admin/runtime changes always win and are never reset by this seed.
update public.site_settings set
  store_name = case when store_name = '' then 'GEAR//DROP' else store_name end,
  default_seo_title = case when default_seo_title = '' then 'GEAR//DROP — Beyblade X per la community italiana' else default_seo_title end,
  default_seo_description = coalesce(default_seo_description, 'Trottole, lanciatori, stadi e accessori Beyblade X. Prodotti originali, spedizione veloce in tutta Italia, drop settimanali.')
where singleton
  and updated_by is null
  and store_name = ''
  and default_seo_title = ''
  and default_seo_description is null;

insert into public.shipping_methods (code, name, price_cents, free_from_cents, active, sort_order)
values ('standard', 'Spedizione standard', 490, 5900, false, 0)
on conflict (code) do update set
  name = excluded.name,
  price_cents = excluded.price_cents,
  free_from_cents = excluded.free_from_cents,
  sort_order = excluded.sort_order;

insert into public.order_enablement_checks (key, label)
values
  ('owners', 'Due owner verificati'),
  ('environment', 'Ambiente e segreti verificati'),
  ('stock', 'Stock reale caricato e revisionato'),
  ('availability', 'Override disponibilita revisionati'),
  ('shipping', 'Metodi di spedizione attivi e verificati'),
  ('coupons', 'Coupon revisionati'),
  ('rls', 'Isolamento RLS verificato'),
  ('concurrency', 'Concorrenza e overselling verificati'),
  ('advisors', 'Advisor sicurezza e performance verificati'),
  ('smoke_orders', 'Ordini guest e autenticati verificati'),
  ('backup', 'Backup e ripristino verificati')
on conflict (key) do update set label = excluded.label;
commit;
