-- Generated by scripts/generate-supabase-seed.ts. Do not add secrets.
-- Reruns refresh catalogue copy but deliberately preserve real stock, availability
-- overrides, preorder allocations, operational activation flags, and order settings.

insert into public.site_settings (singleton, accept_orders)
values (true, false)
on conflict (singleton) do nothing;

insert into public.categories (
  slug, name, tagline, description, active, sort_order, publication_status, published_at
)
values
  ('beyblade-x', 'Beyblade X', 'Scatena la tua energia. Domina lo stadio.', 'Tutta la collezione di trottole Beyblade X: attacco, difesa, stamina e bilanciate, pronte per ogni scontro.', true, 0, 'published'::public.publication_status, now()),
  ('lanciatori', 'Lanciatori', 'Potenza e controllo nelle tue mani.', 'Lanciatori a corda e accessori di lancio per colpi precisi e ripetibili.', true, 1, 'published'::public.publication_status, now()),
  ('stadi', 'Stadi', 'Arene per battaglie epiche.', 'Stadi e set arena ufficiali Beyblade X, studiati per urti estremi e KO spettacolari.', true, 2, 'published'::public.publication_status, now()),
  ('accessori', 'Accessori', 'Personalizza. Migliora. Vinci.', 'Attrezzi, custodie e ricambi per tenere il tuo arsenale sempre pronto.', true, 3, 'published'::public.publication_status, now())
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  sort_order = excluded.sort_order;

with seed(category_slug, slug, sku, name, tagline, description, price_cents, compare_at_price_cents, blade_type, rating, review_count, sort_order) as (
  values
  ('stadi', 'stadio-beystadium-x-attack-set', 'stadio-beystadium-x-attack-set', 'Stadio Beystadium X Attack Set', 'Arena, 2 trottole e 2 lanciatori inclusi.', 'Lo Stadium X Attack Set è l''arena definitiva per chi ama l''azione senza compromessi. La sua forma esclusiva guida le trottole verso il centro, aumentando la frequenza degli urti e le possibilità di KO spettacolari. Il set include 2 trottole ufficiali Beyblade X e 2 lanciatori di precisione, per sfide epiche subito pronte all''azione.', 4999, null, null, 4.8, 237, 0),
  ('beyblade-x', 'wizard-arrow-4-80b', 'wizard-arrow-4-80b', 'Wizard Arrow 4-80B', 'Equilibrio perfetto tra velocità e impatto.', 'Wizard Arrow 4-80B unisce una linea aggressiva a un assetto stabile: accelera in curva e mantiene la traiettoria anche dopo gli urti più duri. Una scelta solida per chi costruisce combo d''attacco affidabili.', 2499, null, 'attacco', 4.5, 1230, 1),
  ('beyblade-x', 'cobalt-dragoon-2-60c', 'cobalt-dragoon-2-60c', 'Cobalt Dragoon 2-60C Starter Pack', 'Potenza esplosiva. Colpisci senza pietà.', 'Cobalt Dragoon 2-60C combina un design aggressivo con prestazioni bilanciate per offrire attacchi devastanti e stabilità costante. Ideale per blader che vogliono imporsi in ogni scontro. Lo starter pack include il lanciatore a corda.', 3499, null, 'attacco', 4.5, 987, 2),
  ('beyblade-x', 'phoenix-wing-9-60gf', 'phoenix-wing-9-60gf', 'Phoenix Wing 9-60GF', 'Resistenza e controllo in ogni scontro.', 'Phoenix Wing 9-60GF è costruita per durare: assorbe gli urti e restituisce rotazione, logorando gli avversari fino all''ultimo giro. La scelta di chi vince ai punti.', 2499, null, 'bilanciato', 4.5, 845, 3),
  ('beyblade-x', 'shark-edge-3-60lf', 'shark-edge-3-60lf', 'Shark Edge 3-60LF', 'Difesa solida. Resisti fino alla fine.', 'Shark Edge 3-60LF è pensata per incassare: profilo basso, baricentro compatto e un bordo che devia gli attacchi invece di subirli. Chi prova a spingerti fuori se ne pentirà.', 2499, null, 'difesa', 4.5, 612, 4),
  ('beyblade-x', 'dran-sword-4-80db', 'dran-sword-4-80db', 'Dran Sword 4-80DB', 'Stamina infinita. Non fermarti mai.', 'Dran Sword 4-80DB gira, e gira ancora. Dispersione minima e assetto pulito per portare il duello alla distanza e chiuderlo quando gli altri si sono già fermati.', 2499, null, 'stamina', 4.5, 543, 5),
  ('beyblade-x', 'dran-buster-1-60a', 'dran-buster-1-60a', 'Dran Buster 1-60A', 'Impatto puro. Chiudi il match al primo colpo.', 'Dran Buster 1-60A concentra tutta la massa dove serve: sull''urto. Costruita per chi non vuole aspettare i punti e preferisce chiudere con un KO.', 2499, null, 'attacco', 4.5, 112, 6),
  ('stadi', 'sneak-attack-battle-set', 'sneak-attack-battle-set', 'Sneak Attack Battle Set', 'Il set completo per iniziare a vincere.', 'Sneak Attack Battle Set mette in scatola tutto quello che serve per il primo scontro: arena, trottole e lanciatori. Ordina ora, spediamo appena disponibile.', 6499, null, null, 4.6, 58, 7)
)
insert into public.products (
  category_id, slug, sku, name, tagline, description, price_cents,
  compare_at_price_cents, publication_status, active, stock_quantity,
  blade_type, rating, review_count, sort_order
)
select
  category.id,
  seed.slug,
  seed.sku,
  seed.name,
  seed.tagline,
  seed.description,
  seed.price_cents,
  seed.compare_at_price_cents::integer,
  'published'::public.publication_status,
  true,
  0 as stock_quantity,
  seed.blade_type::public.blade_type,
  seed.rating,
  seed.review_count,
  seed.sort_order
from seed
join public.categories as category on category.slug = seed.category_slug
on conflict (slug) do update set
  category_id = excluded.category_id,
  sku = excluded.sku,
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  publication_status = excluded.publication_status,
  active = excluded.active,
  blade_type = excluded.blade_type,
  rating = excluded.rating,
  review_count = excluded.review_count,
  sort_order = excluded.sort_order;

with seed(product_slug, src, width, height, alt, sort_order) as (
  values
  ('stadio-beystadium-x-attack-set', '/products/stadio-beystadium-x-attack-set-1.png', 530, 472, 'Stadio Beystadium X Attack Set con arena verde, due trottole e due lanciatori', 0),
  ('wizard-arrow-4-80b', '/products/wizard-arrow-4-80b-1.png', 213, 195, 'Trottola Wizard Arrow 4-80B nera e oro', 0),
  ('cobalt-dragoon-2-60c', '/products/cobalt-dragoon-2-60c-1.png', 430, 459, 'Confezione Cobalt Dragoon 2-60C con lanciatore blu e trottola', 0),
  ('cobalt-dragoon-2-60c', '/products/cobalt-dragoon-2-60c-2.png', 261, 171, 'Lanciatore blu e trottola Cobalt Dragoon 2-60C', 1),
  ('phoenix-wing-9-60gf', '/products/phoenix-wing-9-60gf-1.png', 189, 167, 'Trottola Phoenix Wing 9-60GF rossa e oro', 0),
  ('shark-edge-3-60lf', '/products/shark-edge-3-60lf-1.png', 194, 155, 'Trottola Shark Edge 3-60LF argento e teal', 0),
  ('dran-sword-4-80db', '/products/dran-sword-4-80db-1.png', 191, 151, 'Trottola Dran Sword 4-80DB bianca e viola con lanciatore', 0),
  ('dran-buster-1-60a', '/products/dran-buster-1-60a-1.png', 176, 165, 'Trottola Dran Buster 1-60A rossa e argento', 0),
  ('sneak-attack-battle-set', '/products/sneak-attack-battle-set-1.png', 172, 168, 'Confezione Sneak Attack Battle Set', 0)
)
insert into public.product_images (product_id, src, width, height, alt, sort_order, published)
select product.id, seed.src, seed.width, seed.height, seed.alt, seed.sort_order, true
from seed
join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  src = excluded.src,
  width = excluded.width,
  height = excluded.height,
  alt = excluded.alt,
  published = excluded.published;

with seed(product_slug, label, value, sort_order) as (
  values
  ('stadio-beystadium-x-attack-set', 'Tipo', 'Kit arena', 0),
  ('stadio-beystadium-x-attack-set', 'Sistema', 'Beyblade X', 1),
  ('stadio-beystadium-x-attack-set', 'Componenti', '1 stadio, 2 trottole, 2 lanciatori', 2),
  ('stadio-beystadium-x-attack-set', 'Materiale', 'Plastica e metallo', 3),
  ('wizard-arrow-4-80b', 'Tipo', 'Attacco', 0),
  ('wizard-arrow-4-80b', 'Sistema', 'Beyblade X', 1),
  ('wizard-arrow-4-80b', 'Componenti', '1 Top', 2),
  ('wizard-arrow-4-80b', 'Materiale', 'Plastica e metallo', 3),
  ('cobalt-dragoon-2-60c', 'Tipo', 'Attacco', 0),
  ('cobalt-dragoon-2-60c', 'Sistema', 'Beyblade X', 1),
  ('cobalt-dragoon-2-60c', 'Componenti', '1 Top, 1 Lancia a corda', 2),
  ('cobalt-dragoon-2-60c', 'Materiale', 'Plastica e metallo', 3),
  ('phoenix-wing-9-60gf', 'Tipo', 'Bilanciato', 0),
  ('phoenix-wing-9-60gf', 'Sistema', 'Beyblade X', 1),
  ('phoenix-wing-9-60gf', 'Componenti', '1 Top', 2),
  ('phoenix-wing-9-60gf', 'Materiale', 'Plastica e metallo', 3),
  ('shark-edge-3-60lf', 'Tipo', 'Difesa', 0),
  ('shark-edge-3-60lf', 'Sistema', 'Beyblade X', 1),
  ('shark-edge-3-60lf', 'Componenti', '1 Top', 2),
  ('shark-edge-3-60lf', 'Materiale', 'Plastica e metallo', 3),
  ('dran-sword-4-80db', 'Tipo', 'Stamina', 0),
  ('dran-sword-4-80db', 'Sistema', 'Beyblade X', 1),
  ('dran-sword-4-80db', 'Componenti', '1 Top, 1 Lancia a corda', 2),
  ('dran-sword-4-80db', 'Materiale', 'Plastica e metallo', 3),
  ('dran-buster-1-60a', 'Tipo', 'Attacco', 0),
  ('dran-buster-1-60a', 'Sistema', 'Beyblade X', 1),
  ('dran-buster-1-60a', 'Componenti', '1 Top', 2),
  ('dran-buster-1-60a', 'Materiale', 'Plastica e metallo', 3),
  ('sneak-attack-battle-set', 'Tipo', 'Kit arena', 0),
  ('sneak-attack-battle-set', 'Sistema', 'Beyblade X', 1),
  ('sneak-attack-battle-set', 'Componenti', '1 stadio, 2 trottole, 2 lanciatori', 2),
  ('sneak-attack-battle-set', 'Materiale', 'Plastica e metallo', 3)
)
insert into public.product_specs (product_id, label, value, sort_order)
select product.id, seed.label, seed.value, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  label = excluded.label,
  value = excluded.value;

with seed(product_slug, title, description, sort_order) as (
  values
  ('stadio-beystadium-x-attack-set', 'Stadio X Attack', 'Design ottimizzato per scontri intensi e KO spettacolari', 0),
  ('stadio-beystadium-x-attack-set', 'Include 2 trottole', 'Pronte all''azione con ottime performance', 1),
  ('stadio-beystadium-x-attack-set', '2 lanciatori inclusi', 'Lanci potenti e precisi per dominare l''arena', 2),
  ('stadio-beystadium-x-attack-set', 'Compatibile Beyblade X', 'Usa tutte le trottole e accessori della serie Beyblade X', 3),
  ('stadio-beystadium-x-attack-set', 'Perfetto per sfide epiche', 'Ideale per duelli 1 contro 1 tra amici e collezionisti', 4),
  ('wizard-arrow-4-80b', 'Assetto d''attacco', 'Massimizza l''aggressività su ogni traiettoria', 0),
  ('wizard-arrow-4-80b', 'Blade 4-80B', 'Bilanciamento tra velocità di rotazione e impatto', 1),
  ('wizard-arrow-4-80b', 'Compatibile Beyblade X', 'Si monta con tutte le parti della serie', 2),
  ('cobalt-dragoon-2-60c', 'Starter pack completo', 'Trottola e lanciatore pronti all''uso', 0),
  ('cobalt-dragoon-2-60c', 'Rotazioni stabili', 'Attacchi rapidi senza perdere il controllo', 1),
  ('cobalt-dragoon-2-60c', 'Compatibile Beyblade X', 'Usa tutte le parti e gli accessori della serie', 2),
  ('phoenix-wing-9-60gf', 'Assetto bilanciato', 'Versatilità totale su attacco e difesa', 0),
  ('phoenix-wing-9-60gf', 'Blade 9-60GF', 'Resistenza agli urti e rotazione prolungata', 1),
  ('phoenix-wing-9-60gf', 'Compatibile Beyblade X', 'Si monta con tutte le parti della serie', 2),
  ('shark-edge-3-60lf', 'Assetto difensivo', 'Resistenza e controllo sotto pressione', 0),
  ('shark-edge-3-60lf', 'Blade 3-60LF', 'Profilo basso che devia gli impatti', 1),
  ('shark-edge-3-60lf', 'Compatibile Beyblade X', 'Si monta con tutte le parti della serie', 2),
  ('dran-sword-4-80db', 'Assetto stamina', 'Durata senza pari sulla lunga distanza', 0),
  ('dran-sword-4-80db', 'Blade 4-80DB', 'Rotazione pulita e dispersione minima', 1),
  ('dran-sword-4-80db', 'Compatibile Beyblade X', 'Si monta con tutte le parti della serie', 2),
  ('dran-buster-1-60a', 'Assetto d''attacco', 'Massa concentrata sull''impatto', 0),
  ('dran-buster-1-60a', 'Blade 1-60A', 'Colpo secco, pensato per il KO', 1),
  ('dran-buster-1-60a', 'Compatibile Beyblade X', 'Si monta con tutte le parti della serie', 2),
  ('sneak-attack-battle-set', 'Set completo', 'Arena, trottole e lanciatori in un''unica confezione', 0),
  ('sneak-attack-battle-set', 'Pronto al gioco', 'Tutto quello che serve per il primo duello', 1),
  ('sneak-attack-battle-set', 'Compatibile Beyblade X', 'Usa tutte le trottole della serie', 2)
)
insert into public.product_features (product_id, title, description, sort_order)
select product.id, seed.title, seed.description, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  title = excluded.title,
  description = excluded.description;

with seed(product_slug, content, sort_order) as (
  values
  ('stadio-beystadium-x-attack-set', '1 × Stadio Beystadium X', 0),
  ('stadio-beystadium-x-attack-set', '2 × Trottole Beyblade X', 1),
  ('stadio-beystadium-x-attack-set', '2 × Lanciatori a corda', 2),
  ('stadio-beystadium-x-attack-set', 'Manuale di gioco', 3),
  ('wizard-arrow-4-80b', '1 × Trottola Wizard Arrow 4-80B', 0),
  ('wizard-arrow-4-80b', 'Manuale', 1),
  ('cobalt-dragoon-2-60c', '1 × Trottola Cobalt Dragoon 2-60C', 0),
  ('cobalt-dragoon-2-60c', '1 × Lanciatore a corda', 1),
  ('cobalt-dragoon-2-60c', 'Manuale', 2),
  ('phoenix-wing-9-60gf', '1 × Trottola Phoenix Wing 9-60GF', 0),
  ('phoenix-wing-9-60gf', 'Manuale', 1),
  ('shark-edge-3-60lf', '1 × Trottola Shark Edge 3-60LF', 0),
  ('shark-edge-3-60lf', 'Manuale', 1),
  ('dran-sword-4-80db', '1 × Trottola Dran Sword 4-80DB', 0),
  ('dran-sword-4-80db', '1 × Lanciatore', 1),
  ('dran-sword-4-80db', 'Manuale', 2),
  ('dran-buster-1-60a', '1 × Trottola Dran Buster 1-60A', 0),
  ('dran-buster-1-60a', 'Manuale', 1),
  ('sneak-attack-battle-set', '1 × Stadio', 0),
  ('sneak-attack-battle-set', '2 × Trottole Beyblade X', 1),
  ('sneak-attack-battle-set', '2 × Lanciatori', 2),
  ('sneak-attack-battle-set', 'Manuale di gioco', 3)
)
insert into public.product_box_contents (product_id, content, sort_order)
select product.id, seed.content, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  content = excluded.content;

with seed(product_slug, tag) as (
  values
  ('stadio-beystadium-x-attack-set', 'novita'),
  ('sneak-attack-battle-set', 'limited')
)
insert into public.product_tags (product_id, tag)
select product.id, seed.tag::public.promo_tag
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, tag) do nothing;

with seed(product_slug, related_slug, sort_order) as (
  values
  ('stadio-beystadium-x-attack-set', 'wizard-arrow-4-80b', 0),
  ('stadio-beystadium-x-attack-set', 'cobalt-dragoon-2-60c', 1),
  ('stadio-beystadium-x-attack-set', 'phoenix-wing-9-60gf', 2),
  ('stadio-beystadium-x-attack-set', 'shark-edge-3-60lf', 3),
  ('wizard-arrow-4-80b', 'cobalt-dragoon-2-60c', 0),
  ('wizard-arrow-4-80b', 'dran-buster-1-60a', 1),
  ('wizard-arrow-4-80b', 'shark-edge-3-60lf', 2),
  ('wizard-arrow-4-80b', 'phoenix-wing-9-60gf', 3),
  ('cobalt-dragoon-2-60c', 'wizard-arrow-4-80b', 0),
  ('cobalt-dragoon-2-60c', 'phoenix-wing-9-60gf', 1),
  ('cobalt-dragoon-2-60c', 'shark-edge-3-60lf', 2),
  ('cobalt-dragoon-2-60c', 'dran-sword-4-80db', 3),
  ('phoenix-wing-9-60gf', 'dran-sword-4-80db', 0),
  ('phoenix-wing-9-60gf', 'shark-edge-3-60lf', 1),
  ('phoenix-wing-9-60gf', 'wizard-arrow-4-80b', 2),
  ('phoenix-wing-9-60gf', 'dran-buster-1-60a', 3),
  ('shark-edge-3-60lf', 'dran-buster-1-60a', 0),
  ('shark-edge-3-60lf', 'phoenix-wing-9-60gf', 1),
  ('shark-edge-3-60lf', 'wizard-arrow-4-80b', 2),
  ('shark-edge-3-60lf', 'cobalt-dragoon-2-60c', 3),
  ('dran-sword-4-80db', 'phoenix-wing-9-60gf', 0),
  ('dran-sword-4-80db', 'cobalt-dragoon-2-60c', 1),
  ('dran-sword-4-80db', 'shark-edge-3-60lf', 2),
  ('dran-sword-4-80db', 'dran-buster-1-60a', 3),
  ('dran-buster-1-60a', 'wizard-arrow-4-80b', 0),
  ('dran-buster-1-60a', 'shark-edge-3-60lf', 1),
  ('dran-buster-1-60a', 'cobalt-dragoon-2-60c', 2),
  ('dran-buster-1-60a', 'dran-sword-4-80db', 3),
  ('sneak-attack-battle-set', 'stadio-beystadium-x-attack-set', 0),
  ('sneak-attack-battle-set', 'wizard-arrow-4-80b', 1),
  ('sneak-attack-battle-set', 'cobalt-dragoon-2-60c', 2),
  ('sneak-attack-battle-set', 'dran-buster-1-60a', 3)
)
insert into public.product_relations (product_id, related_product_id, relation_type, sort_order)
select product.id, related.id, 'related'::public.product_relation_type, seed.sort_order
from seed
join public.products as product on product.slug = seed.product_slug
join public.products as related on related.slug = seed.related_slug
on conflict (product_id, related_product_id, relation_type) do update set
  sort_order = excluded.sort_order;

insert into public.bundles (
  slug, eyebrow, title_line_one, title_line_two, description,
  price_cents, compare_at_price_cents, hero_product_id, active
)
select
  'bundle-campione',
  'Bundle campione',
  'Scatena il',
  'tuo potenziale.',
  'Arena, 2 trottole ad alte prestazioni e 2 lanciatori. Tutto ciò che ti serve per dominare.',
  7999,
  9996,
  product.id,
  true
from public.products as product
where product.slug = 'stadio-beystadium-x-attack-set'
on conflict (slug) do update set
  eyebrow = excluded.eyebrow,
  title_line_one = excluded.title_line_one,
  title_line_two = excluded.title_line_two,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  hero_product_id = excluded.hero_product_id;

with seed(bundle_slug, product_slug, quantity, sort_order) as (
  values
  ('bundle-campione', 'stadio-beystadium-x-attack-set', 1, 0),
  ('bundle-campione', 'wizard-arrow-4-80b', 1, 1),
  ('bundle-campione', 'dran-buster-1-60a', 1, 2)
)
insert into public.bundle_items (bundle_id, product_id, quantity, sort_order)
select bundle.id, product.id, seed.quantity, seed.sort_order
from seed
join public.bundles as bundle on bundle.slug = seed.bundle_slug
join public.products as product on product.slug = seed.product_slug
on conflict (bundle_id, product_id) do update set
  quantity = excluded.quantity,
  sort_order = excluded.sort_order;

insert into public.shipping_methods (code, name, price_cents, free_from_cents, active, sort_order)
values ('standard', 'Spedizione standard', 490, 5900, false, 0)
on conflict (code) do update set
  name = excluded.name,
  price_cents = excluded.price_cents,
  free_from_cents = excluded.free_from_cents,
  sort_order = excluded.sort_order;

insert into public.order_enablement_checks (key, label)
values
  ('owners', 'Due owner verificati'),
  ('environment', 'Ambiente e segreti verificati'),
  ('stock', 'Stock reale caricato e revisionato'),
  ('availability', 'Override disponibilita revisionati'),
  ('shipping', 'Metodi di spedizione attivi e verificati'),
  ('coupons', 'Coupon revisionati'),
  ('rls', 'Isolamento RLS verificato'),
  ('concurrency', 'Concorrenza e overselling verificati'),
  ('advisors', 'Advisor sicurezza e performance verificati'),
  ('smoke_orders', 'Ordini guest e autenticati verificati'),
  ('backup', 'Backup e ripristino verificati')
on conflict (key) do update set label = excluded.label;
