import Link from "next/link";
import { redirect } from "next/navigation";
import { OrderAcceptanceForm } from "@/components/admin/settings/settings-forms";
import styles from "@/components/admin/settings/settings.module.css";
import { requireAdminAccess } from "@/lib/admin/access";
import { loadOrderEnablementChecks,loadStoreSettings } from "@/lib/admin/settings-repository";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic"; export const fetchCache="force-no-store";
export default async function SettingsAdminPage(){const client=await createSupabaseServerClient();const principal=await requireAdminAccess(client);if(principal.role==="editor")redirect("/admin");const [settings,checks]=await Promise.all([loadStoreSettings(client),loadOrderEnablementChecks(client)]);const links=[["/admin/impostazioni/negozio","Negozio","Identità, legale, manutenzione e limiti"],["/admin/impostazioni/seo","SEO","Metadati e anteprima predefinita"],["/admin/impostazioni/contatti","Contatti","Supporto e indirizzo pubblico"],["/admin/impostazioni/social","Social","Canali HTTPS verificati"]] as const;return <div className={styles.page}><header className={styles.heading}><div><p>Sistema / Configurazione</p><h1>Impostazioni</h1><span>Campi relazionali tipizzati · nessun editor JSON</span></div></header><div className={styles.cards}>{links.map(([href,label,description])=><Link className={styles.card} href={href} key={href}><strong>{label}</strong><span>{description}</span></Link>)}</div><section className={styles.checklist}><h2>Checklist attivazione ordini</h2>{checks.map(check=><div className={styles.checkRow} key={check.key}><div><strong>{check.label}</strong><span>{check.evidence??"Nessuna verifica registrata"}</span></div><span className={styles.status}>{check.status}</span></div>)}</section>{principal.role==="owner"?<OrderAcceptanceForm enabled={settings.accept_orders}/>:<p className={styles.error}>Solo il proprietario può attivare o disattivare gli ordini.</p>}</div>}
