"use server";

import { revalidatePath,revalidateTag } from "next/cache";
import { requireStaffRole,requireUser } from "@/lib/auth/guards";
import { contactSettingsSchema,manualOrderCheckSchema,orderAcceptanceSchema,seoSettingsSchema,shippingMethodIdSchema,shippingMethodSchema,socialSettingsSchema,storeSettingsSchema } from "@/lib/admin/settings";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export type SettingsActionState={readonly ok:boolean;readonly message:string};
const MANAGERS=["owner","admin"] as const; const OWNERS=["owner"] as const;
const text=(data:FormData,key:string)=>typeof data.get(key)==="string"?String(data.get(key)):"";
const checked=(data:FormData,key:string)=>data.get(key)==="on";
const nullable=(data:FormData,key:string)=>text(data,key).trim()||null;
const cents=(data:FormData,key:string)=>{const value=text(data,key).trim();return value?Math.round(Number(value.replace(",","."))*100):null;};
async function authorized(roles:typeof MANAGERS|typeof OWNERS){const client=await createSupabaseServerClient();await requireUser(client);const principal=await requireStaffRole(client,roles);return {client,principal};}
function refresh(){revalidateTag("settings","max");revalidateTag("shipping","max");revalidateTag("storefront","max");revalidatePath("/admin");revalidatePath("/admin/spedizioni");revalidatePath("/admin/impostazioni");revalidatePath("/");revalidatePath("/checkout");}
const fail=(message="Operazione non completata. Controlla i dati e riprova."):SettingsActionState=>({ok:false,message});

export async function saveShippingMethodAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{
  const parsed=shippingMethodSchema.safeParse({id:text(formData,"id")||undefined,name:text(formData,"name"),code:text(formData,"code"),description:nullable(formData,"description"),priceCents:cents(formData,"price"),freeFromCents:cents(formData,"freeFrom"),countryCodes:text(formData,"countryCodes").split(",").map(value=>value.trim()).filter(Boolean),estimateMinDays:text(formData,"estimateMinDays"),estimateMaxDays:text(formData,"estimateMaxDays"),active:checked(formData,"active"),sortOrder:text(formData,"sortOrder")});
  if(!parsed.success)return fail("Controlla costi, aree ISO, stime e ordinamento.");
  try{const {client}=await authorized(MANAGERS);const input=parsed.data;const record={name:input.name,code:input.code,description:input.description,price_cents:input.priceCents,free_from_cents:input.freeFromCents,enabled_country_codes:input.countryCodes,estimate_min_days:input.estimateMinDays,estimate_max_days:input.estimateMaxDays,active:input.active,sort_order:input.sortOrder};const result=input.id?await client.from("shipping_methods").update(record).eq("id",input.id):await client.from("shipping_methods").insert(record);if(result.error)return fail("Metodo di spedizione non salvato.");refresh();return {ok:true,message:"Metodo di spedizione salvato."};}catch{return fail("Permessi insufficienti o sessione scaduta.");}
}

export async function deleteShippingMethodAction(formData:FormData):Promise<void>{const id=shippingMethodIdSchema.parse(text(formData,"id"));const {client}=await authorized(MANAGERS);const result=await client.from("shipping_methods").delete().eq("id",id);if(result.error)throw new Error("Metodo di spedizione non eliminato");refresh();}

export async function saveStoreSettingsAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{
  const parsed=storeSettingsSchema.safeParse({storeName:text(formData,"storeName"),legalName:text(formData,"legalName"),vatNumber:nullable(formData,"vatNumber"),taxCode:nullable(formData,"taxCode"),currency:text(formData,"currency"),maxQuantityPerLine:text(formData,"maxQuantityPerLine"),legalNotice:nullable(formData,"legalNotice"),maintenanceMode:checked(formData,"maintenanceMode"),maintenanceMessage:nullable(formData,"maintenanceMessage"),uploadMaxBytes:Number(text(formData,"uploadMaxMb"))*1_048_576});
  if(!parsed.success)return fail("Controlla identità, limiti e manutenzione.");
  try{const {client,principal}=await authorized(OWNERS);const value=parsed.data;const result=await client.from("site_settings").update({store_name:value.storeName,legal_name:value.legalName,vat_number:value.vatNumber,tax_code:value.taxCode,currency:value.currency,max_quantity_per_line:value.maxQuantityPerLine,legal_notice:value.legalNotice,maintenance_mode:value.maintenanceMode,maintenance_message:value.maintenanceMessage,upload_max_bytes:value.uploadMaxBytes,updated_by:principal.userId}).eq("singleton",true);if(result.error)return fail();refresh();return {ok:true,message:"Impostazioni negozio salvate."};}catch{return fail("Solo il proprietario può modificare queste impostazioni.");}
}

export async function saveSeoSettingsAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{const parsed=seoSettingsSchema.safeParse({title:text(formData,"title"),description:nullable(formData,"description"),ogImageUrl:nullable(formData,"ogImageUrl")});if(!parsed.success)return fail("Controlla lunghezze e URL HTTPS.");try{const {client,principal}=await authorized(OWNERS);const value=parsed.data;const result=await client.from("site_settings").update({default_seo_title:value.title,default_seo_description:value.description,default_og_image_url:value.ogImageUrl,updated_by:principal.userId}).eq("singleton",true);if(result.error)return fail();refresh();return {ok:true,message:"SEO predefinito salvato."};}catch{return fail("Solo il proprietario può modificare il SEO.");}}

export async function saveContactSettingsAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{const parsed=contactSettingsSchema.safeParse({supportEmail:nullable(formData,"supportEmail"),supportPhone:nullable(formData,"supportPhone"),streetAddress:nullable(formData,"streetAddress"),city:nullable(formData,"city"),postalCode:nullable(formData,"postalCode"),countryCode:text(formData,"countryCode")});if(!parsed.success)return fail("Controlla email, contatti e codice paese ISO.");try{const {client,principal}=await authorized(OWNERS);const value=parsed.data;const result=await client.from("site_settings").update({support_email:value.supportEmail,support_phone:value.supportPhone,street_address:value.streetAddress,city:value.city,postal_code:value.postalCode,country_code:value.countryCode,updated_by:principal.userId}).eq("singleton",true);if(result.error)return fail();refresh();return {ok:true,message:"Contatti salvati."};}catch{return fail("Solo il proprietario può modificare i contatti.");}}

export async function saveSocialSettingsAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{const parsed=socialSettingsSchema.safeParse({instagramUrl:nullable(formData,"instagramUrl"),facebookUrl:nullable(formData,"facebookUrl"),tiktokUrl:nullable(formData,"tiktokUrl"),youtubeUrl:nullable(formData,"youtubeUrl")});if(!parsed.success)return fail("Usa solo URL HTTPS validi.");try{const {client,principal}=await authorized(OWNERS);const value=parsed.data;const result=await client.from("site_settings").update({instagram_url:value.instagramUrl,facebook_url:value.facebookUrl,tiktok_url:value.tiktokUrl,youtube_url:value.youtubeUrl,updated_by:principal.userId}).eq("singleton",true);if(result.error)return fail();refresh();return {ok:true,message:"Canali social salvati."};}catch{return fail("Solo il proprietario può modificare i social.");}}

export async function setOrderAcceptanceAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{const enabled=text(formData,"enabled")==="true";const parsed=orderAcceptanceSchema.safeParse({enabled,confirmation:text(formData,"confirmation")});if(!parsed.success)return fail(enabled?"Digita esattamente ATTIVA ORDINI.":"Digita esattamente DISATTIVA ORDINI.");try{const {client}=await authorized(OWNERS);const result=await client.rpc("set_order_acceptance",{p_enabled:enabled,p_confirmation:parsed.data.confirmation});if(result.error){if(result.error.message.includes("GD_ORDER_CHECKLIST_INCOMPLETE"))return fail("Checklist incompleta: risolvi tutti i controlli prima di attivare.");return fail();}refresh();return {ok:true,message:enabled?"Accettazione ordini attivata.":"Accettazione ordini disattivata."};}catch{return fail("Solo il proprietario può cambiare l’accettazione ordini.");}}

export async function setManualOrderCheckAction(_state:SettingsActionState,formData:FormData):Promise<SettingsActionState>{const parsed=manualOrderCheckSchema.safeParse({key:text(formData,"key"),status:text(formData,"status"),evidence:text(formData,"evidence")});if(!parsed.success)return fail("Seleziona un controllo, un esito e inserisci evidenza verificabile.");try{const {client}=await authorized(OWNERS);const result=await client.rpc("set_manual_order_enablement_check",{p_key:parsed.data.key,p_status:parsed.data.status,p_evidence:parsed.data.evidence});if(result.error)return fail("Controllo operativo non aggiornato.");refresh();return {ok:true,message:"Controllo operativo registrato e auditato."};}catch{return fail("Solo il proprietario può verificare i controlli operativi.");}}
