"use server";

import { revalidatePath,revalidateTag } from "next/cache";import { requireStaffRole,requireUser } from "@/lib/auth/guards";import { inviteStaffSchema,teamRevokeSchema,teamRoleChangeSchema,teamStatusSchema } from "@/lib/admin/team";import { createSupabaseServerClient } from "@/lib/supabase/server";
export type TeamActionState={readonly ok:boolean;readonly message:string};const OWNERS=["owner"] as const;const text=(data:FormData,key:string)=>typeof data.get(key)==="string"?String(data.get(key)):"";const fail=(message="Operazione team non completata."):TeamActionState=>({ok:false,message});
async function ownerClient(){const client=await createSupabaseServerClient();await requireUser(client);const principal=await requireStaffRole(client,OWNERS);return {client,principal};}function refresh(userId?:string){revalidateTag("team","max");revalidateTag("audit","max");revalidatePath("/admin/team");revalidatePath("/admin/attivita");if(userId)revalidatePath(`/admin/team/${userId}`);}

export async function inviteStaffAction(_state:TeamActionState,formData:FormData):Promise<TeamActionState>{const parsed=inviteStaffSchema.safeParse({email:text(formData,"email"),displayName:text(formData,"displayName"),role:text(formData,"role")});if(!parsed.success)return fail("Controlla email, nome e ruolo.");try{const {client}=await ownerClient();const { createPrivilegedSupabaseClient }=await import("@/lib/supabase/admin");const privileged=createPrivilegedSupabaseClient();const invited=await privileged.auth.admin.inviteUserByEmail(parsed.data.email,{data:{display_name:parsed.data.displayName}});if(invited.error||!invited.data.user)return fail("Invito non completato. Verifica l’indirizzo e riprova.");const inserted=await client.rpc("record_staff_invite",{p_user_id:invited.data.user.id,p_email:parsed.data.email,p_display_name:parsed.data.displayName,p_role:parsed.data.role});if(inserted.error){await privileged.auth.admin.deleteUser(invited.data.user.id);return fail("Invito non completato. Verifica l’indirizzo e riprova.");}refresh(invited.data.user.id);return {ok:true,message:"Invito inviato e profilo staff creato."};}catch{return fail("Invito non completato. Verifica la configurazione server.");}}

export async function changeStaffRoleAction(_state:TeamActionState,formData:FormData):Promise<TeamActionState>{const parsed=teamRoleChangeSchema.safeParse({userId:text(formData,"userId"),role:text(formData,"role")});if(!parsed.success)return fail("Ruolo o membro non valido.");try{const {client}=await ownerClient();const result=await client.rpc("change_staff_role",{p_user_id:parsed.data.userId,p_role:parsed.data.role});if(result.error)return fail(result.error.message.includes("GD_STAFF_LAST_OWNER")?"L’ultimo proprietario attivo non può essere modificato.":result.error.message.includes("GD_STAFF_SELF_CHANGE")?"Non puoi cambiare il tuo ruolo da questa schermata.":undefined);refresh(parsed.data.userId);return {ok:true,message:"Ruolo aggiornato."};}catch{return fail("Solo il proprietario può cambiare i ruoli.");}}

export async function setStaffActiveAction(_state:TeamActionState,formData:FormData):Promise<TeamActionState>{const parsed=teamStatusSchema.safeParse({userId:text(formData,"userId"),active:text(formData,"active")==="true"});if(!parsed.success)return fail("Stato membro non valido.");try{const {client}=await ownerClient();const result=await client.rpc("set_staff_active",{p_user_id:parsed.data.userId,p_active:parsed.data.active});if(result.error)return fail(result.error.message.includes("GD_STAFF_LAST_OWNER")?"L’ultimo proprietario deve restare attivo.":"Stato non aggiornato.");refresh(parsed.data.userId);return {ok:true,message:parsed.data.active?"Accesso riattivato.":"Accesso disattivato."};}catch{return fail("Solo il proprietario può cambiare lo stato.");}}

export async function revokeStaffAccessAction(_state:TeamActionState,formData:FormData):Promise<TeamActionState>{const parsed=teamRevokeSchema.safeParse({userId:text(formData,"userId"),confirmation:text(formData,"confirmation")});if(!parsed.success)return fail("Digita esattamente REVOCA ACCESSO.");try{const {client}=await ownerClient();const result=await client.rpc("revoke_staff_access",{p_user_id:parsed.data.userId});if(result.error)return fail(result.error.message.includes("GD_STAFF_LAST_OWNER")?"L’ultimo proprietario non può essere revocato.":"Revoca non completata.");refresh(parsed.data.userId);return {ok:true,message:"Accesso revocato."};}catch{return fail("Solo il proprietario può revocare accessi.");}}
