"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { savePromotionAction } from "@/app/admin/actions/promotions";
import type { PricingResources, PromotionEditorData } from "@/lib/admin/promotion-repository";
import styles from "./pricing.module.css";

const initialState={ok:false,message:""}; const local=(value:string|null|undefined)=>value?.slice(0,16)??""; const euros=(cents:number)=> (cents/100).toFixed(2);
export function PromotionForm({data,resources}:{readonly data:PromotionEditorData|null;readonly resources:PricingResources}){
 const [state,action,pending]=useActionState(savePromotionAction,initialState); const [dirty,setDirty]=useState(false); const router=useRouter(); const promotion=data?.promotion; const [kind,setKind]=useState(promotion?.discount_kind??"percentage");
 useEffect(()=>{if(state.ok){queueMicrotask(()=>setDirty(false));router.refresh();}},[router,state.ok]); useEffect(()=>{const unload=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault();};window.addEventListener("beforeunload",unload);return()=>window.removeEventListener("beforeunload",unload);},[dirty]);
 return <form action={action} className={styles.form} onChange={()=>setDirty(true)}>{promotion?<input name="id" type="hidden" value={promotion.id}/>:null}<header><div><p>PROMOTION / {promotion?.id??"NEW"}</p><h2>{promotion?.name??"Nuova promozione"}</h2></div>{dirty?<span>Modifiche non salvate</span>:null}</header><div className={styles.grid}>
  <label>Nome<input defaultValue={promotion?.name??""} name="name" required/></label><label>Tipo<select name="discountKind" onChange={event=>setKind(event.target.value as "percentage"|"fixed"|"promotional_price")} value={kind}><option value="percentage">Percentuale</option><option value="fixed">Importo fisso</option><option value="promotional_price">Prezzo promozionale</option></select></label>
  <label className={styles.wide}>Descrizione<textarea defaultValue={promotion?.description??""} name="description" rows={4}/></label><label>{kind==="percentage"?"Percentuale":"Valore in euro"}<input defaultValue={promotion?kind==="percentage"?promotion.discount_value:euros(promotion.discount_value):""} min="0.01" name="discountValue" required step={kind==="percentage"?"1":"0.01"} type="number"/></label><label>Minimo ordine €<input defaultValue={promotion?euros(promotion.minimum_subtotal_cents):"0.00"} min="0" name="minimumSubtotal" step="0.01" type="number"/></label><label>Quantità minima<input defaultValue={promotion?.minimum_quantity??1} min="1" name="minimumQuantity" type="number"/></label><label>Priorità<input defaultValue={promotion?.priority??0} name="priority" type="number"/></label><label>Inizio<input defaultValue={local(promotion?.starts_at)} name="startsAt" type="datetime-local"/></label><label>Fine<input defaultValue={local(promotion?.ends_at)} name="endsAt" type="datetime-local"/></label><label className={styles.check}><input defaultChecked={promotion?.stackable??false} name="stackable" type="checkbox"/>Cumulabile</label><label className={styles.check}><input defaultChecked={promotion?.active??false} name="active" type="checkbox"/>Attiva</label>
 </div><section><h3>Prodotti coinvolti</h3><div className={styles.targets}><Target label="Prodotti" name="productIds" options={resources.products} selected={data?.productIds??[]}/><Target label="Categorie" name="categoryIds" options={resources.categories} selected={data?.categoryIds??[]}/><Target label="Bundle" name="bundleIds" options={resources.bundles} selected={data?.bundleIds??[]}/></div></section><div className={styles.preview}><strong>Anteprima target reale</strong>{data?.affectedProducts.length?<ul>{data.affectedProducts.map(item=><li key={item.id}>{item.label} · {item.meta}</li>)}</ul>:<p>Nessun prodotto diretto salvato. I target categoria/bundle vengono risolti dal pricing autorevole.</p>}</div>{state.message?<p className={state.ok?styles.success:styles.error}>{state.message}</p>:null}<div className={styles.actions}><button disabled={pending} type="submit">{pending?"Salvataggio…":"Salva promozione"}</button></div></form>;
}
function Target({label,name,options,selected}:{readonly label:string;readonly name:string;readonly options:PricingResources["products"];readonly selected:readonly number[]}){return <label className={styles.target}>{label}<select defaultValue={selected.map(String)} multiple name={name} size={Math.min(8,Math.max(4,options.length))}>{options.map(item=><option key={item.id} value={item.id}>{item.label} · {item.meta}</option>)}</select></label>}
