import { writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { BUNDLE, CATEGORIES, FREE_SHIPPING_THRESHOLD, PRODUCTS, SHIPPING_FLAT_RATE } from "../src/data/catalog";
import {
  CONTENT_PAGE_SEEDS,
  FOOTER_COLUMN_SEEDS,
  HOMEPAGE_SECTION_SEEDS,
  INITIAL_PUBLIC_SETTINGS,
  NAVIGATION_MENU_SEEDS,
} from "../src/data/content-seed";

function text(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function nullableText(value: string | undefined): string {
  return value === undefined ? "null" : text(value);
}

function nullable(value: string | null | undefined): string {
  return value == null ? "null" : text(value);
}

function rows(values: readonly string[]): string {
  return values.map((value) => `  (${value})`).join(",\n");
}

export function generateSupabaseSeed(): string {
  const categoryRows = CATEGORIES.map((category, index) =>
    [
      text(category.slug), text(category.name), text(category.tagline), text(category.description),
      "true", index, "'published'::public.publication_status", "now()",
    ].join(", "),
  );
  const productRows = PRODUCTS.map((product, index) =>
    [
      text(product.category),
      text(product.slug),
      text(product.slug),
      text(product.name),
      text(product.tagline),
      text(product.description),
      product.price.amount,
      product.compareAtPrice?.amount ?? "null",
      nullableText(product.bladeType),
      product.rating,
      product.reviewCount,
      index,
    ].join(", "),
  );
  const imageRows = PRODUCTS.flatMap((product) =>
    product.images.map((image, index) =>
      [text(product.slug), text(image.src), image.width, image.height, text(image.alt), index].join(", "),
    ),
  );
  const specRows = PRODUCTS.flatMap((product) =>
    product.specs.map((spec, index) =>
      [text(product.slug), text(spec.label), text(spec.value), index].join(", "),
    ),
  );
  const featureRows = PRODUCTS.flatMap((product) =>
    product.features.map((feature, index) =>
      [text(product.slug), text(feature.title), text(feature.description), index].join(", "),
    ),
  );
  const contentRows = PRODUCTS.flatMap((product) =>
    product.boxContents.map((content, index) => [text(product.slug), text(content), index].join(", ")),
  );
  const tagRows = PRODUCTS.flatMap((product) =>
    product.tags.map((tag) => [text(product.slug), text(tag)].join(", ")),
  );
  const relationRows = PRODUCTS.flatMap((product) =>
    product.relatedSlugs.map((relatedSlug, index) =>
      [text(product.slug), text(relatedSlug), index].join(", "),
    ),
  );
  const bundleItemRows = BUNDLE.includes.map((slug, index) =>
    [text(BUNDLE.slug), text(slug), 1, index].join(", "),
  );
  const homepageRows = HOMEPAGE_SECTION_SEEDS.map((section, index) => [
    text(section.key), text(section.type), nullable(section.eyebrow), text(section.title),
    nullable(section.subtitle), nullable(section.description), nullable(section.cta?.label),
    nullable(section.cta?.href), "'published'::public.publication_status", "now()", "true", index,
  ].join(", "));
  const homepageProductRows = HOMEPAGE_SECTION_SEEDS.flatMap((section) =>
    (section.productSlugs ?? []).map((slug, index) => [text(section.key), text(slug), index].join(", ")),
  );
  const homepageCategoryRows = HOMEPAGE_SECTION_SEEDS.flatMap((section) =>
    (section.categorySlugs ?? []).map((slug, index) => [text(section.key), text(slug), index].join(", ")),
  );
  const homepageBundleRows = HOMEPAGE_SECTION_SEEDS.flatMap((section) =>
    (section.bundleSlugs ?? []).map((slug, index) => [text(section.key), text(slug), index].join(", ")),
  );
  const pageRows = CONTENT_PAGE_SEEDS.map((page) => [
    text(page.slug), text(page.title), text(page.excerpt), text(page.markdownSource),
    "'markdown'::public.content_format", text(page.seoTitle), text(page.seoDescription),
    "'published'::public.publication_status", "now()", "true", page.sortOrder,
  ].join(", "));
  const menuRows = NAVIGATION_MENU_SEEDS.map((menu) => [
    text(menu.key), text(menu.label), "'published'::public.publication_status", "now()", "true",
  ].join(", "));
  const navigationRows = NAVIGATION_MENU_SEEDS.flatMap((menu) =>
    menu.items.map((item, index) => [text(menu.key), text(item.label), text(item.href), index].join(", ")),
  );
  const footerColumnRows = FOOTER_COLUMN_SEEDS.map((column, index) =>
    [text(column.key), text(column.title), "'published'::public.publication_status", "now()", "true", index].join(", "),
  );
  const footerItemRows = FOOTER_COLUMN_SEEDS.flatMap((column) =>
    column.links.map((item, index) => [text(column.key), text(item.label), text(item.href), index].join(", ")),
  );

  return `-- Generated by scripts/generate-supabase-seed.ts. Do not add secrets.
-- Bootstrap-only seed: reruns are allowed before staff or operational activity exists.
-- Never run this file against an operated database.

begin;

do $$
begin
  if exists(select 1 from public.staff_profiles)
    or exists(select 1 from public.orders)
    or exists(select 1 from public.inventory_movements)
    or exists(select 1 from public.audit_events) then
    raise exception using errcode='55000',message='GD_SEED_OPERATED_DATABASE';
  end if;
end;
$$;

insert into public.site_settings (singleton, accept_orders)
values (true, false)
on conflict (singleton) do nothing;

insert into public.categories (
  slug, name, tagline, description, active, sort_order, publication_status, published_at
)
values
${rows(categoryRows)}
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  sort_order = excluded.sort_order;

with seed(category_slug, slug, sku, name, tagline, description, price_cents, compare_at_price_cents, blade_type, rating, review_count, sort_order) as (
  values
${rows(productRows)}
)
insert into public.products (
  category_id, slug, sku, name, tagline, description, price_cents,
  compare_at_price_cents, publication_status, active, stock_quantity,
  blade_type, rating, review_count, sort_order
)
select
  category.id,
  seed.slug,
  seed.sku,
  seed.name,
  seed.tagline,
  seed.description,
  seed.price_cents,
  seed.compare_at_price_cents::integer,
  'published'::public.publication_status,
  true,
  0 as stock_quantity,
  seed.blade_type::public.blade_type,
  seed.rating,
  seed.review_count,
  seed.sort_order
from seed
join public.categories as category on category.slug = seed.category_slug
on conflict (slug) do update set
  category_id = excluded.category_id,
  sku = excluded.sku,
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  blade_type = excluded.blade_type,
  rating = excluded.rating,
  review_count = excluded.review_count,
  sort_order = excluded.sort_order;

with seed(product_slug, src, width, height, alt, sort_order) as (
  values
${rows(imageRows)}
)
insert into public.product_images (product_id, src, width, height, alt, sort_order, published)
select product.id, seed.src, seed.width, seed.height, seed.alt, seed.sort_order, true
from seed
join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  src = excluded.src,
  width = excluded.width,
  height = excluded.height,
  alt = excluded.alt;

with seed(product_slug, label, value, sort_order) as (
  values
${rows(specRows)}
)
insert into public.product_specs (product_id, label, value, sort_order)
select product.id, seed.label, seed.value, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  label = excluded.label,
  value = excluded.value;

with seed(product_slug, title, description, sort_order) as (
  values
${rows(featureRows)}
)
insert into public.product_features (product_id, title, description, sort_order)
select product.id, seed.title, seed.description, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  title = excluded.title,
  description = excluded.description;

with seed(product_slug, content, sort_order) as (
  values
${rows(contentRows)}
)
insert into public.product_box_contents (product_id, content, sort_order)
select product.id, seed.content, seed.sort_order
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, sort_order) do update set
  content = excluded.content;

with seed(product_slug, tag) as (
  values
${rows(tagRows)}
)
insert into public.product_tags (product_id, tag)
select product.id, seed.tag::public.promo_tag
from seed join public.products as product on product.slug = seed.product_slug
on conflict (product_id, tag) do nothing;

with seed(product_slug, related_slug, sort_order) as (
  values
${rows(relationRows)}
)
insert into public.product_relations (product_id, related_product_id, relation_type, sort_order)
select product.id, related.id, 'related'::public.product_relation_type, seed.sort_order
from seed
join public.products as product on product.slug = seed.product_slug
join public.products as related on related.slug = seed.related_slug
on conflict (product_id, related_product_id, relation_type) do update set
  sort_order = excluded.sort_order;

insert into public.bundles (
  slug, eyebrow, title_line_one, title_line_two, description,
  price_cents, compare_at_price_cents, hero_product_id, active
)
select
  ${text(BUNDLE.slug)},
  ${text(BUNDLE.eyebrow)},
  ${text(BUNDLE.title[0])},
  ${text(BUNDLE.title[1])},
  ${text(BUNDLE.description)},
  ${BUNDLE.price.amount},
  ${BUNDLE.compareAtPrice.amount},
  product.id,
  true
from public.products as product
where product.slug = ${text(BUNDLE.heroSlug)}
on conflict (slug) do update set
  eyebrow = excluded.eyebrow,
  title_line_one = excluded.title_line_one,
  title_line_two = excluded.title_line_two,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  hero_product_id = excluded.hero_product_id;

with seed(bundle_slug, product_slug, quantity, sort_order) as (
  values
${rows(bundleItemRows)}
)
insert into public.bundle_items (bundle_id, product_id, quantity, sort_order)
select bundle.id, product.id, seed.quantity, seed.sort_order
from seed
join public.bundles as bundle on bundle.slug = seed.bundle_slug
join public.products as product on product.slug = seed.product_slug
on conflict (bundle_id, product_id) do update set
  quantity = excluded.quantity,
  sort_order = excluded.sort_order;

insert into public.homepage_sections (
  section_key, section_type, eyebrow, title, subtitle, description, cta_label, cta_href,
  publication_status, published_at, active, sort_order
)
values
${rows(homepageRows)}
on conflict (section_key) do update set
  section_type = excluded.section_type,
  eyebrow = excluded.eyebrow,
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  cta_label = excluded.cta_label,
  cta_href = excluded.cta_href;

delete from public.homepage_section_products as target
using public.homepage_sections as section
where target.section_id = section.id
  and section.section_key in (${HOMEPAGE_SECTION_SEEDS.map((section) => text(section.key)).join(", ")});

with seed(section_key, product_slug, sort_order) as (
  values
${rows(homepageProductRows)}
)
insert into public.homepage_section_products(section_id, product_id, sort_order)
select section.id, product.id, seed.sort_order
from seed
join public.homepage_sections as section on section.section_key = seed.section_key
join public.products as product on product.slug = seed.product_slug
on conflict (section_id, product_id) do update set sort_order = excluded.sort_order;

delete from public.homepage_section_categories as target
using public.homepage_sections as section
where target.section_id = section.id
  and section.section_key in (${HOMEPAGE_SECTION_SEEDS.map((section) => text(section.key)).join(", ")});

with seed(section_key, category_slug, sort_order) as (
  values
${rows(homepageCategoryRows)}
)
insert into public.homepage_section_categories(section_id, category_id, sort_order)
select section.id, category.id, seed.sort_order
from seed
join public.homepage_sections as section on section.section_key = seed.section_key
join public.categories as category on category.slug = seed.category_slug
on conflict (section_id, category_id) do update set sort_order = excluded.sort_order;

delete from public.homepage_section_bundles as target
using public.homepage_sections as section
where target.section_id = section.id
  and section.section_key in (${HOMEPAGE_SECTION_SEEDS.map((section) => text(section.key)).join(", ")});

with seed(section_key, bundle_slug, sort_order) as (
  values
${rows(homepageBundleRows)}
)
insert into public.homepage_section_bundles(section_id, bundle_id, sort_order)
select section.id, bundle.id, seed.sort_order
from seed
join public.homepage_sections as section on section.section_key = seed.section_key
join public.bundles as bundle on bundle.slug = seed.bundle_slug
on conflict (section_id, bundle_id) do update set sort_order = excluded.sort_order;

insert into public.content_pages (
  slug, title, excerpt, markdown_source, format, seo_title, seo_description,
  publication_status, published_at, active, sort_order
)
values
${rows(pageRows)}
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  markdown_source = excluded.markdown_source,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description;

insert into public.navigation_menus(menu_key, label, publication_status, published_at, active)
values
${rows(menuRows)}
on conflict (menu_key) do update set label = excluded.label;

delete from public.navigation_items as item
using public.navigation_menus as menu
where item.menu_id = menu.id
  and menu.menu_key in (${NAVIGATION_MENU_SEEDS.map((menu) => text(menu.key)).join(", ")});

with seed(menu_key, label, href, sort_order) as (
  values
${rows(navigationRows)}
)
insert into public.navigation_items(menu_id, parent_id, label, href, active, sort_order)
select menu.id, null, seed.label, seed.href, true, seed.sort_order
from seed join public.navigation_menus as menu on menu.menu_key = seed.menu_key;

insert into public.footer_columns(column_key, title, publication_status, published_at, active, sort_order)
values
${rows(footerColumnRows)}
on conflict (column_key) do update set
  title = excluded.title;

delete from public.footer_items as item
using public.footer_columns as column_row
where item.column_id = column_row.id
  and column_row.column_key in (${FOOTER_COLUMN_SEEDS.map((column) => text(column.key)).join(", ")});

with seed(column_key, label, href, sort_order) as (
  values
${rows(footerItemRows)}
)
insert into public.footer_items(column_id, label, href, active, sort_order)
select column_row.id, seed.label, seed.href, true, seed.sort_order
from seed join public.footer_columns as column_row on column_row.column_key = seed.column_key;

-- Fill reviewed public identity only while migration defaults are still blank.
-- Later admin/runtime changes always win and are never reset by this seed.
update public.site_settings set
  store_name = case when store_name = '' then ${text(INITIAL_PUBLIC_SETTINGS.storeName)} else store_name end,
  default_seo_title = case when default_seo_title = '' then ${text(INITIAL_PUBLIC_SETTINGS.seoTitle)} else default_seo_title end,
  default_seo_description = coalesce(default_seo_description, ${text(INITIAL_PUBLIC_SETTINGS.seoDescription)})
where singleton
  and updated_by is null
  and store_name = ''
  and default_seo_title = ''
  and default_seo_description is null;

insert into public.shipping_methods (code, name, price_cents, free_from_cents, active, sort_order)
values ('standard', 'Spedizione standard', ${SHIPPING_FLAT_RATE}, ${FREE_SHIPPING_THRESHOLD}, false, 0)
on conflict (code) do update set
  name = excluded.name,
  price_cents = excluded.price_cents,
  free_from_cents = excluded.free_from_cents,
  sort_order = excluded.sort_order;

insert into public.order_enablement_checks (key, label)
values
  ('owners', 'Due owner verificati'),
  ('environment', 'Ambiente e segreti verificati'),
  ('stock', 'Stock reale caricato e revisionato'),
  ('availability', 'Override disponibilita revisionati'),
  ('shipping', 'Metodi di spedizione attivi e verificati'),
  ('coupons', 'Coupon revisionati'),
  ('rls', 'Isolamento RLS verificato'),
  ('concurrency', 'Concorrenza e overselling verificati'),
  ('advisors', 'Advisor sicurezza e performance verificati'),
  ('smoke_orders', 'Ordini guest e autenticati verificati'),
  ('backup', 'Backup e ripristino verificati')
on conflict (key) do update set label = excluded.label;
commit;
`;
}

const invokedPath = process.argv[1];

if (invokedPath && import.meta.url === pathToFileURL(invokedPath).href) {
  writeFileSync("supabase/seed.sql", generateSupabaseSeed(), "utf8");
}
