"use client";

import { useActionState } from "react";
import { deleteShippingMethodAction,saveContactSettingsAction,saveSeoSettingsAction,saveShippingMethodAction,saveSocialSettingsAction,saveStoreSettingsAction,setManualOrderCheckAction,setOrderAcceptanceAction,type SettingsActionState } from "@/app/admin/actions/settings";
import type { Database } from "@/lib/supabase/database.types";
import styles from "./settings.module.css";

type Settings=Database["public"]["Tables"]["site_settings"]["Row"];
type Shipping=Database["public"]["Tables"]["shipping_methods"]["Row"];
const initial:SettingsActionState={ok:false,message:""};
const feedback=(state:SettingsActionState)=>state.message?<p className={state.ok?styles.success:styles.error} role="status">{state.message}</p>:null;
const euro=(value:number|null)=>value===null?"":(value/100).toFixed(2);

function ShippingFields({method}:{readonly method:Shipping|null}){return <div className={styles.grid}><label>Nome<input defaultValue={method?.name??""} maxLength={160} name="name" required/></label><label>Codice<input defaultValue={method?.code??""} maxLength={80} name="code" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label className={styles.wide}>Descrizione<textarea defaultValue={method?.description??""} maxLength={1000} name="description" rows={3}/></label><label>Costo EUR<input defaultValue={euro(method?.price_cents??0)} min="0" name="price" required step="0.01" type="number"/></label><label>Gratis da EUR<input defaultValue={euro(method?.free_from_cents??null)} min="0.01" name="freeFrom" step="0.01" type="number"/></label><label>Paesi ISO, separati da virgola<input defaultValue={method?.enabled_country_codes.join(", ")??"IT"} name="countryCodes" required/></label><label>Stima minima giorni<input defaultValue={method?.estimate_min_days??1} min="0" name="estimateMinDays" required type="number"/></label><label>Stima massima giorni<input defaultValue={method?.estimate_max_days??5} min="0" name="estimateMaxDays" required type="number"/></label><label>Ordine<input defaultValue={method?.sort_order??0} name="sortOrder" required type="number"/></label><label className={styles.check}><input defaultChecked={method?.active??true} name="active" type="checkbox"/>Attivo</label></div>}
export function ShippingMethodForm({method}:{readonly method:Shipping|null}){const[state,action,pending]=useActionState(saveShippingMethodAction,initial);return <form action={action} className={styles.form}>{method?<input name="id" type="hidden" value={method.id}/>:null}<header><div><p>SPEDIZIONE / {method?.code??"NUOVA"}</p><h2>{method?.name??"Nuovo metodo"}</h2></div></header><ShippingFields method={method}/>{feedback(state)}<div className={styles.actions}><button disabled={pending} type="submit">{pending?"Salvataggio…":"Salva metodo"}</button>{method?<button className={styles.secondary} formAction={deleteShippingMethodAction} type="submit">Elimina</button>:null}</div></form>}

export function StoreSettingsForm({settings}:{readonly settings:Settings}){const[state,action,pending]=useActionState(saveStoreSettingsAction,initial);return <form action={action} className={styles.form}><div className={styles.grid}><label>Nome negozio<input defaultValue={settings.store_name} maxLength={160} name="storeName" required/></label><label>Ragione sociale<input defaultValue={settings.legal_name} maxLength={200} name="legalName" required/></label><label>Partita IVA<input defaultValue={settings.vat_number??""} maxLength={32} name="vatNumber"/></label><label>Codice fiscale<input defaultValue={settings.tax_code??""} maxLength={32} name="taxCode"/></label><label>Valuta<select defaultValue={settings.currency} name="currency"><option value="EUR">EUR</option></select></label><label>Quantità massima per riga<input defaultValue={settings.max_quantity_per_line} min="1" name="maxQuantityPerLine" type="number"/></label><label>Upload massimo MB<input defaultValue={settings.upload_max_bytes/1_048_576} max="50" min="1" name="uploadMaxMb" type="number"/></label><label className={styles.check}><input defaultChecked={settings.maintenance_mode} name="maintenanceMode" type="checkbox"/>Modalità manutenzione</label><label className={styles.wide}>Messaggio manutenzione<textarea defaultValue={settings.maintenance_message??""} maxLength={1000} name="maintenanceMessage" rows={3}/></label><label className={styles.wide}>Informazioni legali<textarea defaultValue={settings.legal_notice??""} maxLength={10000} name="legalNotice" rows={7}/></label></div>{feedback(state)}<button disabled={pending} type="submit">{pending?"Salvataggio…":"Salva negozio"}</button></form>}

export function SeoSettingsForm({settings}:{readonly settings:Settings}){const[state,action,pending]=useActionState(saveSeoSettingsAction,initial);return <form action={action} className={styles.form}><div className={styles.grid}><label className={styles.wide}>Titolo predefinito<input defaultValue={settings.default_seo_title} maxLength={70} name="title"/></label><label className={styles.wide}>Descrizione predefinita<textarea defaultValue={settings.default_seo_description??""} maxLength={180} name="description" rows={4}/></label><label className={styles.wide}>Immagine Open Graph HTTPS<input defaultValue={settings.default_og_image_url??""} name="ogImageUrl" type="url"/></label></div><div className={styles.preview}><span>Anteprima sicura</span><strong>{settings.default_seo_title||"Titolo non impostato"}</strong><p>{settings.default_seo_description||"Nessuna descrizione predefinita."}</p></div>{feedback(state)}<button disabled={pending} type="submit">{pending?"Salvataggio…":"Salva SEO"}</button></form>}

export function ContactSettingsForm({settings}:{readonly settings:Settings}){const[state,action,pending]=useActionState(saveContactSettingsAction,initial);return <form action={action} className={styles.form}><div className={styles.grid}><label>Email supporto<input defaultValue={settings.support_email??""} name="supportEmail" type="email"/></label><label>Telefono<input defaultValue={settings.support_phone??""} maxLength={40} name="supportPhone"/></label><label className={styles.wide}>Indirizzo<input defaultValue={settings.street_address??""} maxLength={240} name="streetAddress"/></label><label>Città<input defaultValue={settings.city??""} maxLength={120} name="city"/></label><label>CAP<input defaultValue={settings.postal_code??""} maxLength={20} name="postalCode"/></label><label>Paese ISO<input defaultValue={settings.country_code} maxLength={2} name="countryCode" required/></label></div>{feedback(state)}<button disabled={pending} type="submit">{pending?"Salvataggio…":"Salva contatti"}</button></form>}

export function SocialSettingsForm({settings}:{readonly settings:Settings}){const[state,action,pending]=useActionState(saveSocialSettingsAction,initial);return <form action={action} className={styles.form}><div className={styles.grid}>{([['instagramUrl','Instagram',settings.instagram_url],['facebookUrl','Facebook',settings.facebook_url],['tiktokUrl','TikTok',settings.tiktok_url],['youtubeUrl','YouTube',settings.youtube_url]] as const).map(([name,label,value])=><label className={styles.wide} key={name}>{label}<input defaultValue={value??""} name={name} placeholder="https://" type="url"/></label>)}</div>{feedback(state)}<button disabled={pending} type="submit">{pending?"Salvataggio…":"Salva social"}</button></form>}

export function OrderAcceptanceForm({enabled}:{readonly enabled:boolean}){const[state,action,pending]=useActionState(setOrderAcceptanceAction,initial);const confirmation=enabled?"DISATTIVA ORDINI":"ATTIVA ORDINI";return <form action={action} className={styles.activation}><input name="enabled" type="hidden" value={String(!enabled)}/><div><span>Stato corrente</span><strong>{enabled?"Ordini attivi":"Ordini disattivati"}</strong><p>Digita esattamente <code>{confirmation}</code>. La checklist viene riletta nel database.</p></div><label>Conferma<input autoComplete="off" name="confirmation" required/></label><button disabled={pending} type="submit">{pending?"Verifica…":enabled?"Disattiva ordini":"Attiva ordini"}</button>{feedback(state)}</form>}

export function PaymentEnablementCheckForm(){const[state,action,pending]=useActionState(setManualOrderCheckAction,initial);return <form action={action} className={styles.activation}><input name="key" type="hidden" value="payments"/><div><span>Controllo manuale</span><strong>Provider pagamenti</strong><p>Registra soltanto un esito realmente verificato. La modifica viene auditata.</p></div><label>Esito<select name="status" required><option value="passed">Superato</option><option value="failed">Fallito</option></select></label><label>Evidenza<input maxLength={1000} minLength={3} name="evidence" required/></label><button disabled={pending} type="submit">{pending?"Registrazione…":"Registra verifica"}</button>{feedback(state)}</form>}
