import { readFileSync } from "node:fs";import { join } from "node:path";import { describe,expect,it } from "vitest";import { inviteStaffSchema,normalizeAuditQuery,summarizeAuditState,teamRoleChangeSchema } from "@/lib/admin/team";
describe("team and audit admin",()=>{
  it("validates invites and lifecycle targets",()=>{expect(inviteStaffSchema.safeParse({email:"owner@example.com",displayName:"Owner",role:"admin"}).success).toBe(true);expect(inviteStaffSchema.safeParse({email:"bad",displayName:"",role:"root"}).success).toBe(false);expect(teamRoleChangeSchema.safeParse({userId:"00000000-0000-0000-0000-000000000001",role:"editor"}).success).toBe(true);});
  it("normalizes bounded activity filters",()=>{expect(normalizeAuditQuery({operator:"00000000-0000-0000-0000-000000000001",action:" staff. ",entity:" products ",from:"2026-07-01",to:"bad",page:"0"})).toEqual({operator:"00000000-0000-0000-0000-000000000001",action:"staff.",entity:"products",from:"2026-07-01",to:null,page:1,pageSize:50});});
  it("formats only allowlisted scalar audit state",()=>{expect(summarizeAuditState({role:"admin",active:true,email:"secret@example.com",shipping_address_snapshot:{city:"Roma"}})).toEqual(["Ruolo: admin","Attivo: sì"]);expect(summarizeAuditState(null)).toEqual([]);});
  it("authorizes owner before creating a privileged Auth client",()=>{const source=readFileSync(join(process.cwd(),"src/app/admin/actions/team.ts"),"utf8");const guard=source.indexOf("requireStaffRole");const privileged=source.indexOf("createPrivilegedSupabaseClient");expect(guard).toBeGreaterThan(0);expect(privileged).toBeGreaterThan(guard);expect(source).toContain("inviteUserByEmail");expect(source).not.toContain("NEXT_PUBLIC_SUPABASE_SECRET");});
  it("uses generic invite errors and lifecycle RPCs",()=>{const source=readFileSync(join(process.cwd(),"src/app/admin/actions/team.ts"),"utf8");expect(source).toContain("Invito non completato");for(const rpc of ["change_staff_role","set_staff_active","revoke_staff_access"])expect(source).toContain(`rpc(\"${rpc}\"`);});
  it("renders team and activity without raw JSON",()=>{for(const file of ["team/page.tsx","team/[id]/page.tsx","attivita/page.tsx"]){const source=readFileSync(join(process.cwd(),"src/app/admin/(protected)",file),"utf8");expect(source).not.toContain("JSON.stringify");}});
});
